Repository Talend/data-prep, pull requests merged in 2018-10, with the labels that each got.

#1649 feat(TDP-5907): buttons colors
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/PreparationActions.java
  dataprep-webapp/src/app/components/dataset/import/_dataset-import.scss
  dataprep-webapp/src/app/components/dataset/import/dataset-import.controller.js
  dataprep-webapp/src/app/components/dataset/preview/dataset-xls-preview.html
  dataprep-webapp/src/app/components/export/export.html
  dataprep-webapp/src/app/components/feedback/feedback.html
  dataprep-webapp/src/app/components/folder/creator/folder-creator.html
  dataprep-webapp/src/app/components/folder/creator/form/folder-creator-form.html
  dataprep-webapp/src/app/components/home/confirm-modal/confirm-modal.html
  dataprep-webapp/src/app/components/home/name-modal/name-modal.html
  dataprep-webapp/src/app/components/inventory/copy-move/inventory-copy-move.html
  dataprep-webapp/src/app/components/lookup/lookup.html
  dataprep-webapp/src/app/components/playground/playground.html
  dataprep-webapp/src/app/components/preparation/copy-move/preparation-copy-move.html
  dataprep-webapp/src/app/components/preparation/creator/form/preparation-creator-form.html
  dataprep-webapp/src/app/components/preparation/creator/preparation-creator.html
  dataprep-webapp/src/app/components/suggestions-stats/column-profile-options/_column-profile-options.scss
  dataprep-webapp/src/app/components/suggestions-stats/column-profile-options/column-profile-options-controller.js
  dataprep-webapp/src/app/components/suggestions-stats/column-profile-options/column-profile-options.html
  dataprep-webapp/src/app/next/components/PreparationCopyMoveModal/PreparationCopyMoveModal.component.js
  dataprep-webapp/src/app/next/settings/settings.json
  dataprep-webapp/src/app/services/confirm/confirm-service.js
  dataprep-webapp/src/app/services/state/confirm/confirm-state-service.js
  dataprep-webapp/src/app/settings/actions/dataset-actions-service.js
  dataprep-webapp/src/app/settings/actions/preparation-actions-service.js
  dataprep-webapp/src/app/settings/actions/preparation-actions-service.spec.js
Labels: frontend, need review

#1654 feat(TDP-5878): Update dataprep-core version to 1.0.2-SNAPSHOT
  dataprep-avro-message/pom.xml
  pom.xml
Labels: backend, enhancement, need review

#1655 fix(TDP-4404): style and simple quote
  dataprep-webapp/src/app/components/suggestions-stats/stats-details/_stats-details.scss
  dataprep-webapp/src/app/components/suggestions-stats/stats-details/stats-details.html
  dataprep-webapp/src/app/css/vendors/_ui.scss
  dataprep-webapp/src/app/css/vendors/_vendors.scss
  dataprep-webapp/src/app/css/vendors/libs/base/_lists.scss
  dataprep-webapp/src/app/index.scss
  dataprep-webapp/src/app/services/filter/adapter/tql-filter-adapter-service.js
  dataprep-webapp/src/app/services/filter/adapter/tql-filter-adapter-service.spec.js
  dataprep-webapp/src/app/services/filter/filter-service.js
  dataprep-webapp/src/app/services/filter/filter-service.spec.js
Labels: frontend, need review

#1656 fix(TDP-3513): fix js error when bar chart value is negative
  dataprep-webapp/src/app/components/widgets/charts/horizontal-barchart/horizontal-barchart-directive.js
  dataprep-webapp/src/app/components/widgets/charts/horizontal-barchart/horizontal-barchart-directive.spec.js
Labels: frontend, need review

#1657 fix: delete on enter
  dataprep-webapp/src/app/components/home/confirm-modal/confirm-modal.html
  dataprep-webapp/src/app/components/widgets/modal/widget-modal-directive.js
Labels: frontend, need review

#1661 fix(TDP-6170): checkbox apply to all cells with this value broken
  dataprep-webapp/src/app/components/datagrid/_datagrid.scss
Labels: bug, frontend

#1653 fix(TDP-4363): import and fetch more progressbar animation
  dataprep-webapp/src/app/components/dataset/upload-status/dataset-upload-status-controller.js
  dataprep-webapp/src/app/components/dataset/upload-status/dataset-upload-status-controller.spec.js
  dataprep-webapp/src/app/components/dataset/upload-status/dataset-upload-status-directive.js
  dataprep-webapp/src/app/components/dataset/upload-status/dataset-upload-status-directive.spec.js
  dataprep-webapp/src/app/components/dataset/upload-status/dataset-upload-status-module.js
  dataprep-webapp/src/app/components/dataset/upload-status/dataset-upload-status.html
  dataprep-webapp/src/app/services/dataset-workflow/update-workflow-service.js
  dataprep-webapp/src/app/services/state/home/home-state-service.js
  dataprep-webapp/src/app/services/state/home/home-state-service.spec.js
  dataprep-webapp/src/app/services/state/state-service.js
Labels: frontend, need review

#1663 feat(TDP-5907): change button color
  dataprep-webapp/package.json
  dataprep-webapp/yarn.lock
Labels: frontend, need review

#1667 feat(TDP-5878): change documentation URL for 2.8.0 release
  dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_string_type_suggestions.json
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_suggestions.json
Labels: backend, need review

#1668 feat(TDP-5878): update version to 7.1.1
  dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties
Labels: backend, need review

#1670 chore: upgrade Talend/ui
  dataprep-webapp/package.json
  dataprep-webapp/src/app/components/widgets-containers/collapsible-panel/collapsible-panel-container.spec.js
  dataprep-webapp/yarn.lock
Labels: frontend, need review

#1674 feat(TDP-6198) : Delete dataset step doesn't remove it from the context
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/FeatureContext.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java
Labels: backend, bug, integration tests, need review

#1673 fix(TDP-5878): add missing translations
  dataprep-webapp/src/i18n/en.json
  dataprep-webapp/src/i18n/fr.json
  dataprep-webapp/src/i18n/ja.json
  dataprep-webapp/src/i18n/zh.json
Labels: frontend, need review

#1681 feat(TDP-6198) : Delete dataset step doesn't remove it from the context
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/FeatureContext.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java
Labels: backend, enhancement, integration tests, need review

#1690 feat(TDP-4135): dynamic app switcher
  dataprep-backend-service/src/main/java/org/talend/dataprep/command/GenericCommand.java
Labels: backend, frontend, need review

#1623 fix(TDP-6093): avoid adding empty folder name
  dataprep-api/src/main/java/org/talend/dataprep/api/service/FolderAPI.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/command/folder/RemoveFolder.java
  dataprep-webapp/src/app/configure.cmf.js
  dataprep-webapp/src/app/next/actions/__tests__/__snapshots__/folder.test.js.snap
  dataprep-webapp/src/app/next/actions/__tests__/folder.test.js
  dataprep-webapp/src/app/next/actions/__tests__/preparation.test.js
  dataprep-webapp/src/app/next/actions/folder.js
  dataprep-webapp/src/app/next/components/FolderCreatorModal/FolderCreatorModal.component.js
  dataprep-webapp/src/app/next/components/FolderCreatorModal/FolderCreatorModal.connect.js
  dataprep-webapp/src/app/next/constants/actions.js
  dataprep-webapp/src/app/next/constants/search.js
  dataprep-webapp/src/app/next/locales/en/tdp-app.json
  dataprep-webapp/src/app/next/locales/en/tui-components.json
  dataprep-webapp/src/app/next/locales/en/tui-forms.json
  dataprep-webapp/src/app/next/locales/fr/tdp-app.json
  dataprep-webapp/src/app/next/locales/fr/tui-components.json
  dataprep-webapp/src/app/next/locales/fr/tui-containers.json
  dataprep-webapp/src/app/next/locales/fr/tui-forms.json
  dataprep-webapp/src/app/next/locales/ja/tdp-app.json
  dataprep-webapp/src/app/next/locales/ja/tui-components.json
  dataprep-webapp/src/app/next/locales/ja/tui-containers.json
  dataprep-webapp/src/app/next/locales/ja/tui-forms.json
  dataprep-webapp/src/app/next/sagas/effects/__tests__/folder.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/preparation.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/folder.effects.js
  dataprep-webapp/src/app/next/sagas/effects/preparation.effects.js
  dataprep-webapp/src/app/next/sagas/watchers/__tests__/folder.saga.test.js
  dataprep-webapp/src/app/next/sagas/watchers/__tests__/preparation.saga.test.js
  dataprep-webapp/src/app/next/sagas/watchers/folder.saga.js
  dataprep-webapp/src/app/next/sagas/watchers/index.js
  dataprep-webapp/src/app/next/sagas/watchers/preparation.saga.js
  dataprep-webapp/src/app/next/services/__tests__/text.service.test.js
  dataprep-webapp/src/app/next/services/text.service.js
  dataprep-webapp/src/app/next/settings/settings.json
Labels: frontend, need review

#1692 feat(TDP-4135): dynamic app switcher
  dataprep-backend-service/src/main/java/org/talend/dataprep/security/NoOpSecurity.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/security/Security.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/command/GenericCommandTest.java
Labels: backend, need review

#1693 fix(TDP-4135): deal with empty url
  dataprep-backend-service/src/main/java/org/talend/dataprep/command/GenericCommand.java
Labels: backend, need review

#1694 fix(TDP-4135): dynamic app switcher
  dataprep-backend-service/src/main/java/org/talend/dataprep/command/GenericCommand.java
Labels: backend, need review

#1699 feat(TDP-4135): dynamic app switcher (#1697)
  dataprep-backend-service/src/main/java/org/talend/dataprep/command/GenericCommand.java
Labels: backend, cherry-pick, need review

#1698 fix(TDP-6233): Add TenancyContext information
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/ReactiveStepMetadataRepository.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/ReactiveStepMetadataRepositoryTest.java
Labels: need review

#1701 chore: upgrade datasetui libs
  dataprep-webapp/config/sass.conf.js
  dataprep-webapp/package.json
  dataprep-webapp/yarn.lock
Labels: bug, frontend, need review

#1695 chore: add folder refactor
  dataprep-webapp/src/app/next/components/App.container.js
  dataprep-webapp/src/app/next/components/FolderCreatorModal/FolderCreatorModal.component.js
  dataprep-webapp/src/app/next/components/FolderCreatorModal/FolderCreatorModal.connect.js
  dataprep-webapp/src/app/next/components/FolderCreatorModal/actions.js
  dataprep-webapp/src/app/next/components/FolderCreatorModal/index.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/folder.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/folder.effects.js
  dataprep-webapp/src/app/next/sagas/watchers/__tests__/folder.saga.test.js
  dataprep-webapp/src/app/next/settings/settings.json
Labels: frontend, need review

#1702 fix(TDP-5883): searching for an alphanumeric value in an integer one
  dataprep-webapp/src/app/services/datagrid/datagrid-service.js
Labels: bug, frontend, need review

#1706 fix(TDP-632): select the 1st left column of the delete one
  dataprep-webapp/src/app/services/state/grid/grid-state-service.js
  dataprep-webapp/src/app/services/state/grid/grid-state-service.spec.js
Labels: bug, frontend, need review

#1707 chore(TDP-5776): front error on 202 failed
  dataprep-webapp/src/app/services/rest/rest-queued-message-interceptor-factory.js
Labels: bug, frontend, need review

#1710 chore: tui update
  dataprep-webapp/package.json
  dataprep-webapp/yarn.lock
Labels: frontend, need review

#1700 fix (TDP-5956/TDP-5534) : improve wait process in integration tests
  dataprep-api/pom.xml
  dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/DataPrepStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/FeatureContextTest.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/FilterStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/PreparationStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/export/AbstractExportSampleStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/OSIntegrationTestUtilTest.java
Labels: Work in progress, backend, integration tests, need review, reviewing

#1682 fix(TDP-6195): fix configuration for on-the-fly update of dataset names in preps
  dataprep-api/src/main/java/org/talend/dataprep/api/service/APIService.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/FolderAPI.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/PreparationAPI.java
  dataprep-api/src/test/java/org/talend/dataprep/api/service/PreparationAPITest.java
  dataprep-api/src/test/java/org/talend/dataprep/api/service/test/APIClientTest.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/DataSetNameInjection.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/DatasetInjection.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/DefaultOwnerInjection.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/Injections.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/preparation/store/file/FileSystemPreparationRepository.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/preparation/store/inmemory/InMemoryPreparationRepository.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java
  dataprep-preparation/src/main/java/org/talend/dataprep/preparation/configuration/DefaultSharedInjection.java
  dataprep-preparation/src/main/java/org/talend/dataprep/preparation/configuration/SharedInjection.java
  dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/DataSetNameInjection.java
  dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
  dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/DataSetNameInjectionTest.java
  dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/PreparationServiceTest.java
Labels: backend, bug, need review
