Repository Talend/data-prep, pull requests merged in 2018-11, with the labels that each got.

#1717 chore: remove not used variables
  dataprep-webapp/src/app/next/components/FolderCreatorModal/FolderCreatorModal.component.js
  dataprep-webapp/src/app/next/components/FolderCreatorModal/FolderCreatorModal.connect.js
  dataprep-webapp/src/app/next/components/FolderCreatorModal/actions.js
  dataprep-webapp/src/app/next/sagas/effects/folder.effects.js
Labels: frontend, need review

#1639 vferreira/feat/TDP-5322-tdatapreprun-spark-mode-test
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/FileStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/FileComparator.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/FileComparatorTest.java
  dataprep-test-api/src/test/resources/data/unitTests/10L3C_base.csv
  dataprep-test-api/src/test/resources/data/unitTests/10L3C_mix.csv
  dataprep-test-api/src/test/resources/data/unitTests/4L3C.csv
Labels: integration tests, reviewing

#1726 feat(TPD-5909): open sample instead of prep
  dataprep-webapp/src/app/configure.cmf.js
  dataprep-webapp/src/app/next/actions/__tests__/__snapshots__/preparation.test.js.snap
  dataprep-webapp/src/app/next/actions/__tests__/preparation.test.js
  dataprep-webapp/src/app/next/actions/preparation.js
  dataprep-webapp/src/app/next/constants/actions.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/preparation.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/preparation.effects.js
  dataprep-webapp/src/app/next/sagas/watchers/preparation.saga.js
  dataprep-webapp/src/app/next/settings/settings.json
Labels: frontend, need review

#1724 chore: Manage 202 on getPreparationContent
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/PreparationStep.java
Labels: need review

#1727 fix(TDP-6046/TDP-6121/TDP-6261): preparation service doesnt handle kafka event correctly
  dataprep-backend-service/src/main/java/org/talend/dataprep/api/preparation/PreparationUtils.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/cache/DataSetSampleCacheKey.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/cache/loader/ResourceLoaderContentCache.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/event/CacheEventProcessingUtil.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/cache/ResourceLoaderContentCacheTest.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/event/DatasetEventUtil.java
  dataprep-preparation/src/main/java/org/talend/dataprep/preparation/event/PreparationEventUtil.java
Labels: wait for another PR

#1734 fix(TDP-4541): remove useless logs
  dataprep-api/src/main/java/org/talend/dataprep/api/service/command/dataset/DataSetDelete.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/command/preparation/DiffMetadata.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/command/preparation/PreparationGet.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/command/preparation/PreparationGetActions.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/exception/error/APIErrorCodes.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/exception/error/DataSetErrorCodes.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/exception/error/PreparationErrorCodes.java
Labels: backend, bug, need review

#1741 chore(TDP-6287): delete restricted information
  dataprep-backend-service/src/test/resources/org/talend/dataprep/schema/html/sales-force.xls
Labels: need review

#1627 feat(TDP-5808): use Map instead of DataTable in IT
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/DataPrepStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/FolderStep.java
Labels: Work in progress, integration tests

#1743 chore(TDP-6287): delete restricted information
  dataprep-backend-service/src/test/java/org/talend/dataprep/schema/html/HtmlSerializerTest.java
  dataprep-backend-service/src/test/resources/org/talend/dataprep/schema/html/sales-force.xls
Labels: need review

#1744 fix(TDP-6278): improve conn leak detector
  dataprep-backend-service/src/main/java/org/talend/dataprep/command/Defaults.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/command/GenericCommand.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/exception/error/CommonErrorCodes.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/io/CloseableResourceWatch.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/util/VariableLevelLog.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/BaseExportStrategy.java
Labels: backend, enhancement, need review

#1759 fix: typo
  dataprep-webapp/src/i18n/fr.json
Labels: frontend, need review

#1764 fix (TDP-6263): Fix date patterns
  dataprep-dataset/src/test/resources/org/talend/dataprep/dataset/date_time_pattern_expected.json
Labels: backend, enhancement, need review

#1761 fix(TDP-6339): moment and lodash versions
  dataprep-webapp/package.json
  dataprep-webapp/yarn.lock
Labels: frontend, need review

#1735 fix(TDP-6164): fix unicode equivalence in dataSet upload
  dataprep-api/src/main/java/org/talend/dataprep/api/service/DataSetAPI.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/util/StringsHelper.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/util/StringsHelperTest.java
  dataprep-webapp/src/app/services/dataset/rest/dataset-rest-service.js
  dataprep-webapp/src/app/services/preparation/rest/preparation-rest-service.js
  dataprep-webapp/src/app/services/preparation/rest/preparation-rest-service.spec.js
  dataprep-webapp/src/app/services/search/inventory/rest/search-inventory-rest-service.js
  dataprep-webapp/src/app/services/search/inventory/rest/search-inventory-rest-service.spec.js
  dataprep-webapp/src/app/services/utils/url/url-service.js
  dataprep-webapp/src/app/services/utils/url/url-service.spec.js
  dataprep-webapp/src/app/services/utils/utils-module.js
Labels: backend, frontend, need review

#1766 fix(TDP-6208): performance regression on datasets upload
  dataprep-backend-service/src/main/java/org/talend/dataprep/configuration/TaskExecution.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/event/AsyncApplicationListener.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/event/DataPrepEventsCaster.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/configuration/DataPrepEvents.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/BaseDataSetService.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/analysis/asynchronous/AsyncBackgroundAnalysis.java
Labels: backend, bug, need review

#1733 feat(TPD-5102): review modals style
  dataprep-webapp/src/app/components/dataset/import/dataset-import.html
  dataprep-webapp/src/app/components/dataset/preview/dataset-xls-preview.html
  dataprep-webapp/src/app/components/export/export.html
  dataprep-webapp/src/app/components/folder/creator/folder-creator.html
  dataprep-webapp/src/app/components/folder/creator/form/folder-creator-form-component.spec.js
  dataprep-webapp/src/app/components/folder/creator/form/folder-creator-form.html
  dataprep-webapp/src/app/components/folder/selection/_folder-selection.scss
  dataprep-webapp/src/app/components/folder/selection/folder-selection.html
  dataprep-webapp/src/app/components/home/confirm-modal/confirm-modal.html
  dataprep-webapp/src/app/components/home/dataset/home-dataset-container.js
  dataprep-webapp/src/app/components/home/dataset/home-dataset.html
  dataprep-webapp/src/app/components/home/name-modal/name-modal.html
  dataprep-webapp/src/app/components/inventory/copy-move/_inventory-copy-move.scss
  dataprep-webapp/src/app/components/inventory/copy-move/inventory-copy-move.html
  dataprep-webapp/src/app/components/inventory/header/_inventory-header.scss
  dataprep-webapp/src/app/components/inventory/item/_inventory-item.scss
  dataprep-webapp/src/app/components/lookup/_lookup.scss
  dataprep-webapp/src/app/components/lookup/lookup.html
  dataprep-webapp/src/app/components/playground/playground.html
  dataprep-webapp/src/app/components/preparation/copy-move/preparation-copy-move.html
  dataprep-webapp/src/app/components/preparation/creator/form/_preparation-creator-form.scss
  dataprep-webapp/src/app/components/preparation/creator/form/preparation-creator-form-component.spec.js
  dataprep-webapp/src/app/components/preparation/creator/form/preparation-creator-form.html
  dataprep-webapp/src/app/components/preparation/creator/preparation-creator.html
  dataprep-webapp/src/app/components/preparation/picker/preparation-picker.html
  dataprep-webapp/src/app/components/recipe/recipe.html
  dataprep-webapp/src/app/components/step-progress/step-progress.html
  dataprep-webapp/src/app/components/suggestions-stats/actions-list/_actions-list.scss
  dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list.html
  dataprep-webapp/src/app/components/transformation/form/transformation-form-directive.spec.js
  dataprep-webapp/src/app/components/transformation/form/transformation-form.html
  dataprep-webapp/src/app/components/transformation/menu/transformation-menu.html
  dataprep-webapp/src/app/components/widgets/modal/_modal.scss
  dataprep-webapp/src/app/components/widgets/modal/modal.html
  dataprep-webapp/src/app/components/widgets/modal/widget-modal-directive.js
  dataprep-webapp/src/app/components/widgets/modal/widget-modal-directive.spec.js
  dataprep-webapp/src/app/components/widgets/search/_search-input.scss
  dataprep-webapp/src/app/components/widgets/search/widget-search-input-directive.js
  dataprep-webapp/src/app/css/utils/_colors.scss
  dataprep-webapp/src/app/next/components/PreparationCopyMoveModal/PreparationCopyMoveModal.scss
  dataprep-webapp/src/app/next/locales/en/tdp-cmf.json
  dataprep-webapp/src/app/next/locales/fr/tdp-cmf.json
  dataprep-webapp/src/app/next/locales/ja/tdp-cmf.json
  dataprep-webapp/src/app/services/confirm/confirm-service.js
  dataprep-webapp/src/app/services/confirm/confirm-service.spec.js
  dataprep-webapp/src/app/services/import/import-service.js
  dataprep-webapp/src/app/services/import/import-service.spec.js
  dataprep-webapp/src/app/services/state/confirm/confirm-state-service.js
  dataprep-webapp/src/app/services/state/confirm/confirm-state-service.spec.js
  dataprep-webapp/src/app/services/state/search/search-state-service.js
  dataprep-webapp/src/app/services/utils/converter/converter-service.js
  dataprep-webapp/src/app/settings/actions/dataset-actions-service.js
  dataprep-webapp/src/app/settings/actions/modal-actions-service.spec.js
  dataprep-webapp/src/app/settings/actions/preparation-actions-service.js
  dataprep-webapp/src/app/settings/actions/preparation-actions-service.spec.js
  dataprep-webapp/src/i18n/en.json
  dataprep-webapp/src/i18n/fr.json
Labels: frontend, need review

#1758 fix(TDP-6334): move all call to /schema and /content to Preparation
  dataprep-api/src/main/java/org/talend/dataprep/api/service/PreparationAPI.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/DataCatalogClient.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/DatasetClient.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/commands/DataSetGetSchema.java
  dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
Labels: backend, need review

#1762 fix: Avoid 404 on create preparation when errors on get dataset metadata
  dataprep-api/src/main/java/org/talend/dataprep/api/service/PreparationAPI.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/commands/DataSetGetMetadata.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/TransformationServiceTest.java
Labels: backend, need review

#1768 fix(TDP-6339): moment and lodash versions
  dataprep-webapp/package.json
  dataprep-webapp/yarn.lock
Labels: cherry-pick, frontend, need review

#1777 fix(TDP-5102): recipe
  dataprep-webapp/src/app/components/recipe/_recipe.scss
Labels: frontend, need review

#1776 fix(TDP-6208): performance regression on datasets upload (#1766)
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/analysis/asynchronous/AsyncBackgroundAnalysis.java
Labels: Work in progress, backend, bug

#1778 chore: create a webapp profile to skip it entirely
  dataprep-webapp/pom.xml
Labels: frontend, need review

#1770 chore: lodash imports
  dataprep-webapp/src/app/components/transformation/form/transformation-form-controller.js
  dataprep-webapp/src/app/components/widgets/charts/horizontal-barchart/horizontal-barchart-directive.js
  dataprep-webapp/src/app/services/datagrid/datagrid-service.js
  dataprep-webapp/src/app/services/parameters/parameters-service.js
  dataprep-webapp/src/app/services/recipe/recipe-service.js
  dataprep-webapp/src/app/services/state/recipe/recipe-state-service.js
  dataprep-webapp/src/app/services/statistics/date-occurence.worker.js
  dataprep-webapp/src/app/services/statistics/pattern-occurence.worker.js
  dataprep-webapp/src/app/services/statistics/statistics-service.js
  dataprep-webapp/src/app/services/utils/date/date-service.js
  dataprep-webapp/src/app/services/utils/text-format/text-format-service.js
Labels: frontend, need review

#1782 feat(TDP-6376): remove dataset rows number info from lookup
  dataprep-webapp/src/app/components/inventory/item/inventory-item-component.spec.js
  dataprep-webapp/src/app/components/lookup/dataset/list/lookup-dataset-list.html
  dataprep-webapp/src/i18n/en.json
  dataprep-webapp/src/i18n/fr.json
  dataprep-webapp/src/i18n/ja.json
  dataprep-webapp/src/i18n/zh.json
Labels: frontend, need review

#1781 fix(TDP-6318): update Apache tika version to latest (1.19.1)
  dataprep-backend-service/src/main/java/org/talend/dataprep/schema/xls/XlsSchemaParser.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/schema/xls/XlsUtils.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/schema/xls/streaming/StreamingSheet.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/schema/xls/streaming/StreamingWorkbook.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/schema/CompositeFormatDetectorTest.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/schema/html/HtmlDetectorTest.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/schema/xls/streaming/StreamingSheetTest.java
  dataprep-backend-service/src/test/resources/org/talend/dataprep/schema/html/sales-force.xls
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/ExcelComparator.java
Labels: backend, need review

#1784 fix(TDP-6366): Lookup redundant requests
  dataprep-webapp/src/app/components/lookup/lookup-controller.js
  dataprep-webapp/src/app/components/lookup/lookup-controller.spec.js
Labels: enhancement, frontend, need review

#1729 feat(TDP-4992): add dataset name
  dataprep-webapp/package.json
  dataprep-webapp/src/app/components/history-control/history-control-directive.js
  dataprep-webapp/src/app/components/history-control/history-control-directive.spec.js
  dataprep-webapp/src/app/components/history-control/history-control-module.js
  dataprep-webapp/src/app/components/history-control/history-control.html
  dataprep-webapp/src/app/components/playground/_playground.scss
  dataprep-webapp/src/app/components/playground/header/_playground-header.scss
  dataprep-webapp/src/app/components/playground/header/playground-header-component.js
  dataprep-webapp/src/app/components/playground/header/playground-header-component.spec.js
  dataprep-webapp/src/app/components/playground/header/playground-header-controller.js
  dataprep-webapp/src/app/components/playground/header/playground-header-controller.spec.js
  dataprep-webapp/src/app/components/playground/header/playground-header-module.js
  dataprep-webapp/src/app/components/playground/header/playground-header.html
  dataprep-webapp/src/app/components/playground/playground-controller.js
  dataprep-webapp/src/app/components/playground/playground-controller.spec.js
  dataprep-webapp/src/app/components/playground/playground-directive.js
  dataprep-webapp/src/app/components/playground/playground-directive.spec.js
  dataprep-webapp/src/app/components/playground/playground-module.js
  dataprep-webapp/src/app/components/playground/playground.html
  dataprep-webapp/src/app/css/layout/_layout.scss
  dataprep-webapp/src/app/css/vendors/_ui.scss
  dataprep-webapp/src/app/services/playground/playground-service.js
  dataprep-webapp/src/app/services/playground/playground-service.spec.js
  dataprep-webapp/yarn.lock
Labels: frontend, need review

#1772 fix(TDP-6353): update dataset / DatasetDTO conversion
  dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/OwnerInjection.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/commands/DataSetGetSchema.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/conversions/DatasetBeanConversion.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/dataset/adapter/conversions/DatasetBeanConversionTest.java
  dataprep-backend-service/src/test/resources/org/talend/dataprep/dataset/adapter/dataset_payload_example.json
Labels: backend, need review, reviewing
