Repository Talend/data-prep, pull requests merged in 2018-03, with the labels that each got.

#1035 fix(TDP-3481): 'Change Date Format' preparation incorrect target format
  dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
  dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages_fr.properties
  dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages_ja.properties
  dataprep-actions/src/main/resources/org/talend/dataprep/transformation/actions/date/date_patterns.properties
  dataprep-webapp/src/app/components/transformation/form/choice/transformation-choice-param-controller.js
  dataprep-webapp/src/app/components/transformation/form/choice/transformation-choice-param-controller.spec.js
Labels: Merged build failed, backend, frontend, need review

#1153 fix(TDP-3988): Fix cannot chain multiple convert date actions
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/DateCalendarConverter.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/DateCalendarConverterTest.java
Labels: Merged build passed, backend, bug

#1113 TDP-5225 Migration task about creation new column toggle failed
  dataprep-upgrade-common/src/main/java/org/talend/dataprep/upgrade/common/ActionNewColumnToggleCommon.java
  dataprep-upgrade/src/main/java/org/talend/dataprep/upgrade/to_2_3_0_PE/MigrateActionsParameters.java
  dataprep-upgrade/src/test/java/org/talend/dataprep/upgrade/to_2_3_0_PE/MigrateActionsParametersTest.java
Labels: Merged build passed, backend, bug, need review, reviewing

#1161 fix(TDP-3481): fix TUs
  dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/DataSetServiceTest.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/TransformationServiceTest.java
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/service/all_dataset_scope_actions.json
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_string_type_suggestions.json
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_suggestions.json
  dataprep-webapp/src/app/components/transformation/form/choice/transformation-choice-param-controller.js
Labels: Merged build passed, Work in progress, backend

#1158 chore: cleanup in transformer writers
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/TransformerWriter.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/JsonWriter.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/ObjectBuffer.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/XlsWriter.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/pipeline/model/DiffWriterNode.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/pipeline/model/WriterNode.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/format/JsonWriterTest.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/format/XlsWriterTest.java
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/format/expected_columns.json
Labels: Merged build failed, backend, need review

#1165 feat(TDP-5214): update OS integration tests (#1105)
  dataprep-api/src/test/java/org/talend/dataprep/helper/api/Action.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/OSRunnerConfigurationTest.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ActionStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/OSIntegrationTestUtil.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/OSIntegrationTestUtilTest.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/folder/OSFolderUtil.java
  dataprep-test-api/src/test/resources/data/10L3C_processed.csv
  dataprep-test-api/src/test/resources/features/ChangeDatePatternActionTest.feature
  dataprep-test-api/src/test/resources/features/ExportFormatXLSXResult.feature
  dataprep-test-api/src/test/resources/features/ExportPreparationFromCSV.feature
  dataprep-test-api/src/test/resources/features/ExportPreparationFromXLSX.feature
  dataprep-test-api/src/test/resources/features/SearchAndReplaceActionTest.feature
  dataprep-test-api/src/test/resources/features/SmokeTest.feature
  dataprep-test-api/src/test/resources/features/SplitActionTest.feature
  dataprep-test-api/src/test/resources/features/TrimActionTest.feature
  dataprep-test-api/src/test/resources/features/onprem/DatasetCache.feature
Labels: Merged build passed

#1159 fix(TDP-4961) Integration test with DI jobs
  dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/SpringContextConfiguration.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/BackendProperties.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/DataPrepStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java
Labels: Merged build failed, backend, integration tests, need review

#1119 chore(TDP-4974): Bump Jackson versions
  dataprep-actions/pom.xml
  dataprep-api/src/main/java/org/talend/dataprep/api/service/command/transformation/SuggestLookupActions.java
  dataprep-backend-common/pom.xml
  dataprep-backend-service/src/main/java/org/talend/dataprep/command/Defaults.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/configuration/BaseContent.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/configuration/Converters.java
  dataprep-backend/pom.xml
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/configuration/PreviewConfiguration.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java
  dataprep-upgrade/src/main/java/org/talend/dataprep/upgrade/to_2_1_0_PE/SplitReplaceOnValueAction.java
Labels: Merged build passed, backend, enhancement

#1164 chore(TDP-5351): Remove obsolete code in actions
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/column/CreateNewColumn.java
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/phonenumber/FormatPhoneNumber.java
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/text/Split.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/column/CreateNewColumnTest.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/phonenumber/FormatPhoneNumberTest.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/text/SplitTest.java
  dataprep-actions/src/test/resources/org/talend/dataprep/transformation/actions/column/createNewColumnAction_oldStyle.json
  dataprep-actions/src/test/resources/org/talend/dataprep/transformation/actions/text/splitActionOldParam.json
  dataprep-upgrade-common/src/main/java/org/talend/dataprep/upgrade/common/ActionCreateNewColumn.java
  dataprep-upgrade-common/src/main/java/org/talend/dataprep/upgrade/common/SplitParametersUpgrade.java
Labels: Merged build passed, backend, need review

#1168 fix(TDP-4527): remove remote config
  dataprep-api/src/main/resources/application.properties
  dataprep-backend-service/src/main/java/org/talend/dataprep/ui/UiPropertiesConfiguration.java
Labels: Merged build passed, backend, need review

#1156 fix(TDP-4084): lazy jackson parsing
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/common/ActionsUtils.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/DataSet.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/DataSetDataReader.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/LightweightExportableDataSetUtils.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/json/DataSetRowIterator.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/json/DataSetRowStreamDeserializer.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/api/action/context/ActionContext.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/Pipeline.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/node/TypeDetectionNode.java
  dataprep-backend-common/src/test/java/org/talend/dataprep/transformation/api/action/context/ActionContextTest.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/command/dataset/DataSetGet.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/transformation/actions/datablending/DataSetLookupRowMatcher.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/TransformerWriter.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/ObjectBuffer.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/pipeline/model/WriterNode.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/ApplyPreparationExportStrategy.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/DataSetExportStrategy.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/OptimizedExportStrategy.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/PreparationExportStrategy.java
Labels: Merged build passed, backend, bug

#1138 chore: update versions in data-prep
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/api/ActionSettings.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/configurer/HeaderbarHelpConfigurerForNonTDPUsers.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/configurer/HeaderbarInformationConfigurer.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/configurer/HeaderbarInformationPlaygroundConfigurer.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/CommonActionsProvider.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/WindowActions.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/views/api/appheaderbar/AppHeaderBarSettings.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/views/provider/HomeViews.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/views/provider/HomeViewsForNonTDPUsers.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/views/provider/PlaygroundViews.java
  dataprep-api/src/test/java/org/talend/dataprep/api/service/AppSettingsAPITest.java
  dataprep-backend-service/src/main/resources/org/talend/dataprep/messages.properties
  dataprep-backend-service/src/main/resources/org/talend/dataprep/messages_fr.properties
  dataprep-webapp/package.json
  dataprep-webapp/src/app/components/widgets-containers/app-header-bar/app-header-bar-container.scss
  dataprep-webapp/src/app/components/widgets-containers/app-header-bar/app-header-bar-container.spec.js
  dataprep-webapp/src/app/components/widgets-containers/app-header-bar/app-header-bar-controller.js
  dataprep-webapp/src/app/components/widgets-containers/app-header-bar/app-header-bar.html
  dataprep-webapp/src/app/index.scss
  dataprep-webapp/src/i18n/en.json
  dataprep-webapp/src/i18n/fr.json
  dataprep-webapp/src/mocks/Settings.mock.js
  dataprep-webapp/yarn.lock
Labels: Merged build passed, need review

#1157 wi(TDP-5248): tabs subline should be brand-primary
  dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/_action-suggestions.scss
  dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/actions-suggestions-controller.js
  dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/actions-suggestions-directive.js
  dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/actions-suggestions-directive.spec.js
  dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/actions-suggestions-module.js
  dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/actions-suggestions.html
  dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/tab-item/tab-item-controller.js
  dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/tab-item/tab-item-controller.spec.js
  dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/tab-item/tab-item-directive.js
  dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/tab-item/tab-item-module.js
  dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/tab-item/tab-item.html
  dataprep-webapp/src/app/components/suggestions-stats/stats-details/_stats-details.scss
  dataprep-webapp/src/app/components/suggestions-stats/stats-details/stats-details-controller.js
  dataprep-webapp/src/app/components/suggestions-stats/stats-details/stats-details-directive.js
  dataprep-webapp/src/app/components/suggestions-stats/stats-details/stats-details-directive.spec.js
  dataprep-webapp/src/app/components/suggestions-stats/stats-details/stats-details.html
  dataprep-webapp/src/app/components/suggestions-stats/tab-item/tab-item.html
  dataprep-webapp/src/app/components/widgets-containers/widgets-containers-module.js
  dataprep-webapp/src/app/index.themed.scss
Labels: bug, frontend, need review

#1160 chore: update RestAssured usage
  dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
  dataprep-backend-service/src/test/java/org/talend/ServiceBaseTest.java
  dataprep-test-api/src/main/resources/application.properties
Labels: integration tests, need review

#1172 fix(TDP-4284): TI-remove custom dico
  dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/FeatureContext.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/PreparationStep.java
Labels: backend, integration tests, need review

#1182 feat(TDP-5376): wait for $translate service is ready
  dataprep-webapp/src/app/index-route.js
Labels: frontend, need review

#1184 chore(TDP-4527): avoid console error regarding theme
  dataprep-webapp/config/webpack.config.js
Labels: frontend, need review

#1179 fix(TDP-5389): app switcher bug
  dataprep-webapp/package.json
  dataprep-webapp/src/app/components/step-progress/_step-progress.scss
  dataprep-webapp/src/app/components/widgets-containers/breadcrumb/breadcrumb-container.spec.js
  dataprep-webapp/src/app/components/widgets/modal/_modal.scss
  dataprep-webapp/yarn.lock
Labels: frontend, need review

#1180 chore: update versions in data-prep
  dataprep-webapp/package.json
  dataprep-webapp/yarn.lock
Labels: need review

#1183 TDP-4961: cherry-pick
  dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
  dataprep-backend-service/src/test/java/org/talend/ServiceBaseTest.java
  dataprep-test-api/src/main/resources/application.properties
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java
Labels: integration tests

#1191 fix(TDP-4084): lazy jackson parsing (#1156)
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/common/ActionsUtils.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/DataSet.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/DataSetDataReader.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/LightweightExportableDataSetUtils.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/json/DataSetRowIterator.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/json/DataSetRowStreamDeserializer.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/api/action/context/ActionContext.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/Pipeline.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/node/TypeDetectionNode.java
  dataprep-backend-common/src/test/java/org/talend/dataprep/transformation/api/action/context/ActionContextTest.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/command/dataset/DataSetGet.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/transformation/actions/datablending/DataSetLookupRowMatcher.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/TransformerWriter.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/ObjectBuffer.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/pipeline/model/WriterNode.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/ApplyPreparationExportStrategy.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/DataSetExportStrategy.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/OptimizedExportStrategy.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/PreparationExportStrategy.java
Labels: bug, need review

#1175 fix(TDP-4084): lazy jackson parsing (#1156)
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/common/ActionsUtils.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/DataSet.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/DataSetDataReader.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/LightweightExportableDataSetUtils.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/json/DataSetRowIterator.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/json/DataSetRowStreamDeserializer.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/api/action/context/ActionContext.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/Pipeline.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/node/TypeDetectionNode.java
  dataprep-backend-common/src/test/java/org/talend/dataprep/transformation/api/action/context/ActionContextTest.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/command/dataset/DataSetGet.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/transformation/actions/datablending/DataSetLookupRowMatcher.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/TransformerWriter.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/ObjectBuffer.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/pipeline/model/WriterNode.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/ApplyPreparationExportStrategy.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/DataSetExportStrategy.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/OptimizedExportStrategy.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/PreparationExportStrategy.java
Labels: bug, need review

#1174 fix(TDP-4084): lazy jackson parsing (#1156)
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/common/ActionsUtils.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/DataSet.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/DataSetDataReader.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/LightweightExportableDataSetUtils.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/json/DataSetRowIterator.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/json/DataSetRowStreamDeserializer.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/api/action/context/ActionContext.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/Pipeline.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/node/TypeDetectionNode.java
  dataprep-backend-common/src/test/java/org/talend/dataprep/transformation/api/action/context/ActionContextTest.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/command/dataset/DataSetGet.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/transformation/actions/datablending/DataSetLookupRowMatcher.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/TransformerWriter.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/ObjectBuffer.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/pipeline/model/WriterNode.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/ApplyPreparationExportStrategy.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/DataSetExportStrategy.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/OptimizedExportStrategy.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/PreparationExportStrategy.java
Labels: bug, need review

#1154 chore(TDP-5393): Run unit tests by default in Integration Tests modules
  dataprep-test-api/README.md
  dataprep-test-api/pom.xml
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/OSRunnerConfigurationIT.java
  dataprep-test-api/src/test/resources/application.properties
  dataprep-test-api/src/test/resources/logback.xml
  pom.xml
Labels: backend, enhancement, need review

#1195 feat(TDP-4891): link to the user preferences in the user menu
  dataprep-backend-service/src/main/resources/org/talend/dataprep/messages.properties
  dataprep-backend-service/src/main/resources/org/talend/dataprep/messages_fr.properties
  dataprep-webapp/src/app/settings/actions/external-actions-service.js
  dataprep-webapp/src/app/settings/actions/external-actions-service.spec.js
Labels: need review

#1198 chore: remove ops version from OS code
  dataprep-api/src/test/java/org/talend/dataprep/api/service/VersionServiceAPITest.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/api/service/info/VersionService.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/configuration/Versions.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/api/service/info/VersionServiceTest.java
Labels: backend, need review

#1199 feat(TDP-5052): TI- check export fullrun S3 runtime
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/export/ExportType.java
Labels: integration tests, need review

#1200 fix(TDP-5414): implements Comparable instead of custom Comparator
  dataprep-async-api/pom.xml
  dataprep-async-api/src/main/java/org/talend/dataprep/async/AsyncExecution.java
  dataprep-async-api/src/test/java/org/talend/dataprep/async/AsyncExecutionTest.java
Labels: backend, enhancement, need review

#1192 feat(TDP-5346): onboarding help
  dataprep-webapp/src/app/services/onboarding/onboarding-preparations-constants.js
  dataprep-webapp/src/i18n/en.json
  dataprep-webapp/src/i18n/fr.json
  dataprep-webapp/yarn.lock
Labels: frontend, need review

#1120 feat(TDP-5234): remove the stacktrace from the logs where missing resource
  dataprep-backend-common/src/main/java/org/talend/dataprep/i18n/ActionsBundle.java
Labels: backend, need review

#1208 wi(TDP-5417): cleanup css to deliver t7 as default
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/context/provider/ContextProvider.java
  dataprep-api/src/main/resources/application.properties
  dataprep-api/src/test/java/org/talend/dataprep/api/service/AppSettingsAPITest.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/ui/UiConfiguration.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/ui/UiPropertiesConfiguration.java
  dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties
  dataprep-webapp/config/sass.conf.js
  dataprep-webapp/config/webpack.config.js
  dataprep-webapp/src/app/components/app/app-directive.spec.js
  dataprep-webapp/src/app/components/app/app.html
  dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-container.scss
  dataprep-webapp/src/app/index.themed.scss
Labels: backend, frontend, need review

#1206 feat(TDP-4575): update Japanese translations
  dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages_ja.properties
  dataprep-backend-service/src/main/resources/org/talend/dataprep/error_messages_ja.properties
  dataprep-backend-service/src/main/resources/org/talend/dataprep/messages_ja.properties
  dataprep-webapp/src/app/services/transformation/transformation-utils-service.js
  dataprep-webapp/src/i18n/en.json
  dataprep-webapp/src/i18n/fr.json
  dataprep-webapp/src/i18n/ja.json
Labels: i18n, need review

#1215 feat(TDP-5366): Display the Dictionary service consumer & producer ve…
  dataprep-api/src/main/java/org/talend/dataprep/api/service/version/AbstractVersionSupplier.java
Labels: backend, need review

#1212 fix(TDP-3505): fix Path traversal issue on Upload Dataset raw API
  dataprep-api/src/main/java/org/talend/dataprep/api/service/command/transformation/SuggestColumnActions.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/DataSetMetadata.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/DataSetMetadataBuilder.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/BaseDataSetService.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/store/content/file/LocalFileContentStore.java
  dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/DataSetServiceTest.java
  dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/analysis/asynchronous/StatisticsAnalysisTest.java
  dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/analysis/synchronous/ContentAnalysisTest.java
  dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/analysis/synchronous/FormatAnalysisTest.java
  dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/analysis/synchronous/QualityAnalysisTest.java
  dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/analysis/synchronous/SchemaAnalysisTest.java
Labels: backend, bug, need review

#1218 feat(TDP-4284): removal a dictionary semantic type
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/analysis/asynchronous/AsyncBackgroundAnalysis.java
Labels: backend, bug, need review

#1219 chore: add Talend maven formatter config
  pom.xml
Labels: enhancement, need review

#1217 feat(TDP-4712): user pref
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/context/provider/ContextProvider.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/api/user/UserData.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/i18n/DataprepLocaleContextResolver.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/security/NoOpSecurity.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/security/Security.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/command/GenericCommandTest.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/i18n/DataprepLocaleContextResolverTest.java
  dataprep-webapp/src/app/index-config.js
  dataprep-webapp/src/app/index-module.js
Labels: backend, frontend, need review

#1207 chore: type progress in AsyncExecution
  dataprep-async-api/src/main/java/org/talend/dataprep/async/AsyncExecution.java
  dataprep-async-api/src/main/java/org/talend/dataprep/async/progress/ExecutionContext.java
  dataprep-async-api/src/main/java/org/talend/dataprep/async/progress/ExecutionProgress.java
Labels: backend, enhancement, need review

#1223 chore(TDP-5475): Change HTTP response statuses
  dataprep-api/src/main/java/org/talend/dataprep/api/service/DataSetAPI.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/command/dataset/DataSetDelete.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/command/folder/RemoveFolder.java
  dataprep-api/src/test/java/org/talend/dataprep/api/service/DataSetAPITest.java
  dataprep-api/src/test/java/org/talend/dataprep/api/service/FolderAPITest.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/command/Defaults.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java
  dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/DataSetServiceTest.java
  dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/FolderService.java
  dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/FolderServiceTest.java
Labels: backend, need review

#1225 fix(TDP-5378): Limit memory used in lookup cache (#1181)
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/datablending/Lookup.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/transformation/actions/datablending/DataSetLookupRowMatcher.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/transformation/actions/datablending/DataSetLookupRowMatcherTest.java
Labels: need review

#1220 feat(TDP-5070) remove snapshots
  dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties
  dataprep-backend/pom.xml
  dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/DataSetServiceTest.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/TransformationServiceTest.java
  pom.xml
Labels: need review

#1231 TDP-5444 close http on body map
  dataprep-backend-service/src/main/java/org/talend/dataprep/command/Defaults.java
Labels: backend, bug, need review

#1234 fix(TDP-5444): pool connection full
  dataprep-api/src/main/java/org/talend/dataprep/api/service/command/preparation/PreparationGetMetadata.java
  dataprep-api/src/test/java/org/talend/dataprep/api/service/PreparationAPITest.java
  dataprep-api/src/test/java/org/talend/dataprep/api/service/test/APIClientTest.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/command/Defaults.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/analysis/asynchronous/AsyncBackgroundAnalysis.java
  dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/analysis/asynchronous/AnalysisEventProcessingTest.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/PreparationStep.java
  dataprep-test-api/src/test/resources/features/PreparationContent.feature
Labels: backend, bug, integration tests, need review

#1235 wi(TDP-5250): buttons colors
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/DatasetActions.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/PreparationActions.java
  dataprep-api/src/test/java/org/talend/dataprep/api/service/AppSettingsAPITest.java
  dataprep-webapp/src/app/components/about/about.html
  dataprep-webapp/src/app/css/components/_intro.scss
Labels: frontend, need review
