Repository Talend/data-prep, pull requests merged in 2018-07, with the labels that each got.

#1421 fix(TDP-5836): recipe arrows style
  dataprep-webapp/src/app/components/widgets/list-item-handler/_list-item-handler.scss
Labels: frontend, need review

#1419 fix(TDP-5668): new Security#asTechnicalUser method for catalog dataset
  dataprep-api/src/main/java/org/talend/dataprep/api/service/DataSetAPI.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/command/dataset/DataSetGetEncodings.java
  dataprep-api/src/main/java/org/talend/dataprep/configuration/APIPreparationConversions.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/security/NoOpSecurityProxy.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/security/SecurityProxy.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java
  dataprep-preparation/src/main/java/org/talend/dataprep/preparation/event/PreparationUpdateListenerUtil.java
  dataprep-preparation/src/test/java/org/talend/dataprep/preparation/event/PreparationUpdateListenerUtilTest.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/ApplyPreparationExportStrategy.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/PreparationExportStrategy.java
Labels: backend, need review

#1430 fix(TDP-5838): fix problems with column name duplication
  dataprep-api/src/test/java/org/talend/dataprep/api/service/PreparationAPITest.java
  dataprep-api/src/test/java/org/talend/dataprep/api/service/test/APIClientTest.java
  dataprep-api/src/test/resources/org/talend/dataprep/api/service/preparations/5L4Ccity_TDP-3858.csv
  dataprep-backend-common/src/main/java/org/talend/dataprep/util/avro/AvroUtils.java
  dataprep-backend-common/src/test/java/org/talend/dataprep/util/avro/AvroUtilsTest.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/DatasetClient.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/dataset/adapter/AvroUtilsTest.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/adapter/DataSetController.java
Labels: backend, bug, need review

#1428 fix(TDP-5822): list DataSetMetada will not fetch the dataset content
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/DataSetMetadata.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/DatasetClient.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/conversions/DatasetBeanConversion.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/user/store/UserDataRepository.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/dataset/adapter/conversions/DatasetBeanConversionTest.java
Labels: backend, need review

#1435 chore(TDP-5595) Set Type as Integer for new column when the mode is Sequence
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/column/CreateNewColumn.java
Labels: backend, bug, need review

#1437 fix(TDP-5865): content is loaded twice when removing all filters after a fetch more
  dataprep-webapp/src/app/services/filter/manager/filter-manager-service.js
Labels: bug, frontend, help wanted, need review

#1440 fix(TDP-5837): missing datagrid headers
  dataprep-webapp/src/app/components/datagrid/services/datagrid-column-service.js
Labels: bug, frontend, need review

#1444 chore: remove unused test file toto.json
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/format/export/json/toto.json
Labels: backend, enhancement, need review

#1436 fix(TDP-5595): fetch more doesn't work most of the time
  dataprep-api/src/test/java/org/talend/dataprep/api/service/AggregationAPITest.java
  dataprep-api/src/test/java/org/talend/dataprep/helper/api/Aggregate.java
  dataprep-api/src/test/resources/org/talend/dataprep/api/service/aggregation/aggregation_expected.json
  dataprep-api/src/test/resources/org/talend/dataprep/api/service/aggregation/aggregation_parameters.json
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/dto/PreparationDetails.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/AggregateStep.java
  dataprep-test-api/src/test/resources/features/Aggregation.feature
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/aggregation/api/AggregationResultTest.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/AggregationTest.java
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/aggregation/aggregation_dataset.csv
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/aggregation/api/aggregation_result.json
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/aggregation/average.json
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/aggregation/average_expected.json
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/aggregation/max.json
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/aggregation/max_expected.json
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/aggregation/min.json
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/aggregation/min_expected.json
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/aggregation/sum.json
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/aggregation/sum_expected.json
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/aggregation/sum_filter.json
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/aggregation/sum_filter_expected.json
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/aggregation/sum_filter_null.json
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/aggregation/uppercase_action.json
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/aggregation/uppercase_sum_expected.json
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/aggregation/uppercase_sum_with_filter_expected.json
Labels: integration tests, need review

#1447 fix(TDP-5838): fix problems with column name duplication (#1430)
  dataprep-api/src/test/java/org/talend/dataprep/api/service/PreparationAPITest.java
  dataprep-api/src/test/java/org/talend/dataprep/api/service/test/APIClientTest.java
  dataprep-api/src/test/resources/org/talend/dataprep/api/service/preparations/5L4Ccity_TDP-3858.csv
  dataprep-backend-common/src/main/java/org/talend/dataprep/util/avro/AvroUtils.java
  dataprep-backend-common/src/test/java/org/talend/dataprep/util/avro/AvroUtilsTest.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/DatasetClient.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/dataset/adapter/AvroUtilsTest.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/adapter/DataSetController.java
Labels: backend, bug, need review

#1454 feat(TDP-5870): create TU for preparation details with version
  dataprep-api/src/test/java/org/talend/dataprep/api/service/test/APIClientTest.java
Labels: backend

#1468 TDP 5890 avro col names
  dataprep-backend-common/src/main/java/org/talend/dataprep/util/avro/AvroUtils.java
  dataprep-backend-common/src/test/java/org/talend/dataprep/util/avro/AvroUtilsTest.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java
Labels: backend, bug, need review

#1481 fix(TDP-5897): fix shared preparation access
  dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/DataSetNameInjection.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java
Labels: backend, bug, need review

#1486 fix(TDP-5898) Previous preparation results are no longer used
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/OptimizedExportStrategy.java
Labels: backend, bug, need review

#1478 fix(Integ tests): fix users switch mecanism
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/User.java
Labels: backend, bug, integration tests, need review

#1488 fix(TDP-5891): Provide dataset rows value when listing TCOMP datasets
  dataprep-backend-common/src/main/java/org/talend/dataprep/dataset/adapter/Dataset.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/DatasetClient.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/conversions/DatasetBeanConversion.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/adapter/conversion/DataSetMetadataBeanConversion.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/analysis/asynchronous/BackgroundAnalysis.java
Labels: backend, need review

#1479 fix(TDP-5894): missing translations
  dataprep-webapp/src/i18n/en.json
  dataprep-webapp/src/i18n/fr.json
  dataprep-webapp/src/i18n/ja.json
Labels: frontend, need review

#1462 chore:(TDP-5832): cmf notifications
  dataprep-webapp/src/app/configure.cmf.js
  dataprep-webapp/src/app/next/actions/__tests__/__snapshots__/notification.test.js.snap
  dataprep-webapp/src/app/next/actions/__tests__/notification.test.js
  dataprep-webapp/src/app/next/actions/index.js
  dataprep-webapp/src/app/next/actions/notification.js
  dataprep-webapp/src/app/next/components/App.container.js
  dataprep-webapp/src/app/next/constants/actions.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/http.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/notification.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/http.effects.js
  dataprep-webapp/src/app/next/sagas/effects/notification.effects.js
  dataprep-webapp/src/app/next/sagas/watchers/__tests__/notification.saga.test.js
  dataprep-webapp/src/app/next/sagas/watchers/index.js
  dataprep-webapp/src/app/next/sagas/watchers/notification.saga.js
Labels: frontend, need review

#1448 fix(TDP-5837): missing datagrid headers (#1440)
  dataprep-webapp/src/app/components/datagrid/services/datagrid-column-service.js
Labels: frontend, need review

#1494 chore: harden sort tool
  dataprep-backend-service/src/main/java/org/talend/dataprep/util/SortAndOrderHelper.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/util/SortAndOrderHelperTest.java
Labels: backend, bug, need review

#1493 fix(TDP-5895): fetch owner in author field
  dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/DefaultOwnerInjection.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/OwnerInjection.java
Labels: backend, bug, need review

#1496 Chore: add logs to control which URLs are really called
  dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
Labels: backend, enhancement, integration tests, need review

#1497 fix(TPSVC-5925): CSV header not disappear when not detected
  dataprep-backend-service/src/main/java/org/talend/dataprep/schema/csv/CSVFormatUtils.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/schema/csv/CSVSchemaParser.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/schema/csv/CSVSchemaParserTest.java
Labels: backend, bug, need review

#1499 Revert "fix(TDP-5895): fetch owner in author field"
  dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/DefaultOwnerInjection.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/OwnerInjection.java
Labels: backend, bug, need review

#1495 fix(TDP-5906): Unable to load content after editing a TCOMP dataset
  dataprep-backend-service/src/main/java/org/talend/dataprep/cache/CacheKeyGenerator.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/cache/DataSetSampleCacheKey.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/event/DatasetEventListener.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/event/DatasetEventUtil.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/analysis/synchronous/SchemaAnalysis.java
  dataprep-preparation/src/main/java/org/talend/dataprep/preparation/event/PreparationEventUtil.java
  dataprep-preparation/src/main/java/org/talend/dataprep/preparation/event/PreparationUpdateListener.java
  dataprep-preparation/src/main/java/org/talend/dataprep/preparation/event/PreparationUpdateListenerUtil.java
  dataprep-preparation/src/test/java/org/talend/dataprep/preparation/event/PreparationEventUtilTest.java
Labels: backend, bug, need review

#1492 fix(TDP-5898): previous preparation results are no longer used
  dataprep-api/src/test/java/org/talend/dataprep/api/service/test/APIClientTest.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/DataSet.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/row/DataSetRow.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/Pipeline.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/api/export/ExportParametersUtil.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ExportPreparationStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/export/AbstractExportSampleStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/export/ExportSampleStep.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/json/PipelineTransformer.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/ApplyPreparationExportStrategy.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/OptimizedExportStrategy.java
Labels: backend, bug, need review

#1483 feat(TDP-5295): semantic types
  dataprep-webapp/package.json
  dataprep-webapp/src/app/configure.cmf.js
  dataprep-webapp/src/app/next/components/__snapshots__/App.container.test.js.snap
  dataprep-webapp/yarn.lock
Labels: frontend, need review

#1506 chore: update snapshots
  dataprep-webapp/src/app/next/components/__snapshots__/App.container.test.js.snap
Labels: bug, frontend, need review

#1505 Revert "Revert "fix(TDP-5895): fetch owner in author field" (#1499)"
  dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/DefaultOwnerInjection.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/OwnerInjection.java
Labels: Work in progress, backend, bug

#1508 chore: fix lint and organize deps
  dataprep-webapp/package.json
  dataprep-webapp/src/app/components/datagrid/services/datagrid-column-service.js
Labels: enhancement, frontend, need review

#1470 fix(TDP-5558): no loading feedback when overwriting a dataset
  dataprep-webapp/src/app/components/home/confirm-modal/confirm-modal-component.js
  dataprep-webapp/src/app/components/home/confirm-modal/confirm-modal.html
  dataprep-webapp/src/app/components/home/confirm-modal/confirm-modal.scss
  dataprep-webapp/src/app/components/home/confirm-modal/confirm-modal.spec.js
  dataprep-webapp/src/app/components/home/home-component.spec.js
  dataprep-webapp/src/app/components/home/home-module.js
  dataprep-webapp/src/app/components/home/home.html
  dataprep-webapp/src/app/components/preparation/copy-move/preparation-copy-move-controller.spec.js
  dataprep-webapp/src/app/components/widgets/confirm/confirm.html
  dataprep-webapp/src/app/components/widgets/confirm/widget-confirm-controller.js
  dataprep-webapp/src/app/components/widgets/confirm/widget-confirm-controller.spec.js
  dataprep-webapp/src/app/components/widgets/confirm/widget-confirm-directive.js
  dataprep-webapp/src/app/components/widgets/confirm/widget-confirm-service.js
  dataprep-webapp/src/app/components/widgets/confirm/widget-confirm-service.spec.js
  dataprep-webapp/src/app/components/widgets/widget-module.js
  dataprep-webapp/src/app/index.scss
  dataprep-webapp/src/app/services/confirm/confirm-module.js
  dataprep-webapp/src/app/services/confirm/confirm-service.js
  dataprep-webapp/src/app/services/confirm/confirm-service.spec.js
  dataprep-webapp/src/app/services/import/import-module.js
  dataprep-webapp/src/app/services/import/import-service.js
  dataprep-webapp/src/app/services/import/import-service.spec.js
  dataprep-webapp/src/app/services/state/confirm/confirm-state-service.js
  dataprep-webapp/src/app/services/state/confirm/confirm-state-service.spec.js
  dataprep-webapp/src/app/services/state/state-module.js
  dataprep-webapp/src/app/services/state/state-service.js
  dataprep-webapp/src/app/settings/actions/dataset-actions-service.js
  dataprep-webapp/src/app/settings/actions/dataset-actions-service.spec.js
  dataprep-webapp/src/app/settings/actions/preparation-actions-service.js
  dataprep-webapp/src/app/settings/actions/preparation-actions-service.spec.js
Labels: bug, enhancement, frontend, need review

#1509 fix(TDP-5925): revert the revert to make TU pass
  dataprep-backend-service/src/main/java/org/talend/dataprep/schema/csv/CSVFormatUtils.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/schema/csv/CSVSchemaParser.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/schema/csv/CSVFormatUtilsTest.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/schema/csv/CSVSchemaParserTest.java
Labels: backend, bug, need review

#1504 add junit to ckeck those action work well for surrogate pair
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/conversions/DistanceConverterTest.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/conversions/DurationConverterTest.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/conversions/TemperaturesConverterTest.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/datamasking/MaskDataByDomainTest.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/dataquality/StandardizeInvalidTest.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/DateCalendarConverterTest.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/DateParserTest.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/fill/FillEmptyFromAboveTest.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/fill/GenerateSequenceTest.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/net/ExtractUrlTokensTest.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/text/RemoveRepeatedCharsTest.java
Labels: backend, need review, reviewing

#1517 feat(TDP-5970): dropdown for expanded list
  dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-container.scss
Labels: frontend, need review

#1523 fix(TDP-5977): Fix missing Zipkin spans for preparation list operation
  dataprep-api/src/main/java/org/talend/dataprep/api/service/FolderAPI.java
Labels: need review

#1520 feat(TDP-5035): add generate uuid action
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/fill/GenerateUUID.java
  dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
  dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages_fr.properties
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/fill/GenerateUUIDTest.java
  dataprep-actions/src/test/resources/org/talend/dataprep/transformation/actions/fill/generateUUIDAction.json
Labels: backend, need review

#1524 chore(Integration Tests): refine requests logging
  dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
  dataprep-api/src/test/java/org/talend/dataprep/helper/VerboseMode.java
  dataprep-test-api/README.md
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/DataPrepStep.java
Labels: backend, enhancement, integration tests

#1525 fix(TDP-5968): Migrate to dataset name in preparation
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/preparation/Preparation.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/preparation/PreparationDTO.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/preparation/PreparationListItemDTO.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/BeanConversionService.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/DataSetNameInjection.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/preparation/store/PersistentPreparation.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/preparation/store/PersistentPreparationRepository.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/util/SortAndOrderHelper.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/util/SortAndOrderHelperTest.java
  dataprep-preparation/src/main/java/org/talend/dataprep/preparation/event/PreparationEventUtil.java
  dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
  dataprep-preparation/src/test/java/org/talend/dataprep/preparation/event/PreparationEventUtilTest.java
Labels: need review

#1528 fix(TDP-5734): first execution of maintenance tasks should be async
  dataprep-maintenance/src/main/java/org/talend/dataprep/maintenance/executor/MaintenanceScheduler.java
  dataprep-maintenance/src/test/java/org/talend/dataprep/maintenance/executor/MaintenanceSchedulerTest.java
Labels: backend, bug, need review

#1529 feat(TDP-5970): dropdown in expanded mode
  dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-container.scss
Labels: need review
