Repository Talend/data-prep, pull requests merged in 2018-05, with the labels that each got.

#1298 chore: upgrade talend/ui to 0.183.0
  dataprep-webapp/package.json
  dataprep-webapp/src/app/components/dataset/import/dataset-import.controller.js
  dataprep-webapp/src/app/components/dataset/import/dataset-import.controller.spec.js
  dataprep-webapp/src/app/css/utils/_colors.scss
Labels: frontend, need review

#1300 feat(TDP-5562): add analytic tags
  dataprep-webapp/src/app/components/lookup/lookup.html
  dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list-controller.js
  dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list-controller.spec.js
  dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list.html
  dataprep-webapp/src/app/components/suggestions-stats/column-profile/column-profile.html
  dataprep-webapp/src/app/components/suggestions-stats/stats-details/stats-details.html
  dataprep-webapp/src/app/components/transformation/form/simple/transformation-simple-param-controller.js
  dataprep-webapp/src/app/components/transformation/form/simple/transformation-simple-param-controller.spec.js
  dataprep-webapp/src/app/components/transformation/form/simple/transformation-simple-param.html
  dataprep-webapp/src/app/components/widgets/charts/horizontal-barchart/horizontal-barchart-directive.js
  dataprep-webapp/src/app/components/widgets/charts/horizontal-barchart/horizontal-barchart-directive.spec.js
  dataprep-webapp/src/app/components/widgets/charts/vertical-barchart/vertical-barchart-directive.js
  dataprep-webapp/src/app/components/widgets/charts/vertical-barchart/vertical-barchart-directive.spec.js
Labels: frontend, need review

#1314 fix: dq tests
  dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/DataSetServiceTest.java
  dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/analysis/synchronous/SchemaAnalysisTest.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/TransformationServiceTest.java
Labels: backend, bug, need review

#1307 fix(TDP-5590): Remove automatic deletion of analyzed dataset
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/BaseDataSetService.java
  dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/DataSetServiceImportTest.java
Labels: backend, bug, need review

#1315 feat(TDP-5562): add analytic tags (#1300)
  dataprep-webapp/src/app/components/lookup/lookup.html
  dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list-controller.js
  dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list-controller.spec.js
  dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list.html
  dataprep-webapp/src/app/components/suggestions-stats/column-profile/column-profile.html
  dataprep-webapp/src/app/components/suggestions-stats/stats-details/stats-details.html
  dataprep-webapp/src/app/components/transformation/form/simple/transformation-simple-param-controller.js
  dataprep-webapp/src/app/components/transformation/form/simple/transformation-simple-param-controller.spec.js
  dataprep-webapp/src/app/components/transformation/form/simple/transformation-simple-param.html
  dataprep-webapp/src/app/components/widgets/charts/horizontal-barchart/horizontal-barchart-directive.js
  dataprep-webapp/src/app/components/widgets/charts/horizontal-barchart/horizontal-barchart-directive.spec.js
  dataprep-webapp/src/app/components/widgets/charts/vertical-barchart/vertical-barchart-directive.js
  dataprep-webapp/src/app/components/widgets/charts/vertical-barchart/vertical-barchart-directive.spec.js
Labels: frontend, need review

#1318 chore: fronted build
  dataprep-webapp/config/webpack.config.dev.js
  dataprep-webapp/package.json
  dataprep-webapp/yarn.lock
Labels: frontend, need review

#1305 feat(TDQ-11891): Add an action to extract phone number informations
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/phonenumber/ExtractPhoneInformation.java
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/phonenumber/FormatPhoneNumber.java
  dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
  dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages_fr.properties
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/net/ExtractUrlTokensTest.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/phonenumber/ExtractPhoneInformationTest.java
  dataprep-actions/src/test/resources/org/talend/dataprep/transformation/actions/phonenumber/extractphoneinformation.json
  dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/api/action/context/TransformationContext.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/suggestion/rules/TypeDomainRules.java
Labels: need review

#1316 fix(TDP-5608): onboarding
  dataprep-webapp/src/app/components/widgets-containers/app-header-bar/app-header-bar-container.scss
  dataprep-webapp/src/app/components/widgets-containers/side-panel/side-panel.scss
  dataprep-webapp/src/app/css/components/_intro.scss
  dataprep-webapp/src/app/index.scss
  dataprep-webapp/src/app/services/onboarding/onboarding-playground-constants.js
  dataprep-webapp/src/app/services/playground/playground-service.js
  dataprep-webapp/src/app/services/playground/playground-service.spec.js
Labels: frontend, need review

#1324 fix(TDP-5608): onboarding
  dataprep-webapp/src/app/components/widgets-containers/app-header-bar/app-header-bar-container.scss
  dataprep-webapp/src/app/components/widgets-containers/side-panel/side-panel.scss
  dataprep-webapp/src/app/css/components/_intro.scss
  dataprep-webapp/src/app/index.scss
  dataprep-webapp/src/app/services/onboarding/onboarding-playground-constants.js
  dataprep-webapp/src/app/services/onboarding/onboarding-service.spec.js
  dataprep-webapp/src/app/services/playground/playground-service.js
  dataprep-webapp/src/app/services/playground/playground-service.spec.js
Labels: frontend, need review

#1326 fix(TDP-5608): onboarding
  dataprep-webapp/src/app/components/widgets-containers/app-header-bar/app-header-bar-container.scss
  dataprep-webapp/src/app/components/widgets-containers/side-panel/side-panel.scss
  dataprep-webapp/src/app/css/components/_intro.scss
  dataprep-webapp/src/app/index.scss
  dataprep-webapp/src/app/services/onboarding/onboarding-playground-constants.js
  dataprep-webapp/src/app/services/onboarding/onboarding-service.spec.js
  dataprep-webapp/src/app/services/playground/playground-service.js
  dataprep-webapp/src/app/services/playground/playground-service.spec.js
Labels: frontend, need review

#1333 fix(TDP-5494) : investigate coverage of IT and GUI-AUTO smoke tests
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ActionStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/PreparationStep.java
Labels: enhancement, integration tests

#1337 fix(TDP-4926) wrong transform strategy
  dataprep-api/src/main/java/org/talend/dataprep/api/service/PreparationAPI.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/TransformAPI.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/command/preparation/PreparationGetContent.java
Labels: backend, need review

#1338 fix(TDP-5254): revert the reverse of additional columns list
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/common/ActionsUtils.java
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/ExtractDateTokens.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/ExtractDateTokensTest.java
Labels: backend, need review

#1340 chore(TDP-5661): Improve rank of phone number actions
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/suggestion/rules/TypeDomainRules.java
Labels: backend, need review

#1345 fix(TDP-1700): Missing unit test update following latest fixes.
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/service/all_dataset_scope_actions.json
Labels: backend, need review

#1344 fix(TDP-5269) Error 500 when performing a aggregation on a column with a range filter
  dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
  dataprep-api/src/test/java/org/talend/dataprep/helper/api/Aggregate.java
  dataprep-api/src/test/java/org/talend/dataprep/helper/api/AggregateOperation.java
  dataprep-api/src/test/java/org/talend/dataprep/helper/api/AggregateResult.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/AggregateStep.java
  dataprep-test-api/src/test/resources/data/scores.csv
  dataprep-test-api/src/test/resources/features/Aggregation.feature
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/TransformerWriter.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/CSVWriter.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/JsonWriter.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/ObjectBuffer.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/XlsWriter.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/pipeline/model/DiffWriterNode.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/pipeline/model/WriterNode.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/format/JsonWriterTest.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/format/XlsWriterTest.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/AggregationTest.java
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/aggregation/uppercase_sum_with_filter_expected.json
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/format/expected_columns.json
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/format/expected_json_with_row_and_metadata.json
Labels: backend, bug

#1341 fix(TDP-5269) Error 500 when performing a aggregation on a column with a range filter
  dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
  dataprep-api/src/test/java/org/talend/dataprep/helper/api/Aggregate.java
  dataprep-api/src/test/java/org/talend/dataprep/helper/api/AggregateOperation.java
  dataprep-api/src/test/java/org/talend/dataprep/helper/api/AggregateResult.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/AggregateStep.java
  dataprep-test-api/src/test/resources/data/scores.csv
  dataprep-test-api/src/test/resources/features/Aggregation.feature
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/JsonWriter.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/format/JsonWriterTest.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/AggregationTest.java
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/aggregation/uppercase_sum_with_filter_expected.json
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/format/expected_json_with_row_and_metadata.json
  dataprep-webapp/src/app/index-module.js
Labels: backend

#1352 chore: upgrade node-sass for all distrib
  dataprep-webapp/package.json
  dataprep-webapp/yarn.lock
Labels: frontend, need review

#1329 feat(TDP-5056) api use catalog endpoints
  dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/DatasetConfiguration.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/commands/DataSetGetContent.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/commands/DataSetGetMetadata.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/commands/DataSetGetSchema.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/commands/DatasetList.java
  dataprep-backend-service/src/test/java/org/talend/ServiceBaseTest.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/dataset/adapter/MockDatasetServer.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/dataset/adapter/commands/DataSetGetSchemaTest.java
  dataprep-backend-service/src/test/resources/org/talend/dataprep/dataset/adapter/dataset_payload_example.json
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/adapter/DataSetController.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/adapter/DataprepDatasetClient.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/adapter/DatasetClient.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/adapter/ProxyDatasetClient.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/adapter/configuration/DatasetClientConfiguration.java
  dataprep-dataset/src/main/resources/application.properties
  dataprep-dataset/src/test/java/org/talend/dataprep/dataset/adapter/DataSetControllerTest.java
  dataprep-dataset/src/test/java/org/talend/dataprep/dataset/adapter/DataprepDatasetClientTest.java
  dataprep-dataset/src/test/java/org/talend/dataprep/dataset/adapter/TestParent.java
Labels: backend

#1346 fix(TDP-5590): Add preparation cleanup on dataset update
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/BaseDataSetService.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/analysis/DataSetAnalyzer.java
  dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/DataSetServiceImportTest.java
  dataprep-preparation/src/main/java/org/talend/dataprep/preparation/event/PreparationUpdateListener.java
  dataprep-preparation/src/main/java/org/talend/dataprep/preparation/event/PreparationUpdateListenerUtil.java
  dataprep-preparation/src/test/java/org/talend/dataprep/preparation/event/PreparationUpdateListenerUtilTest.java
Labels: backend, need review

#1361 fix(TDP-5590): Fix regression in sample update.
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java
Labels: backend, need review
