Repository Talend/data-prep, pull requests merged in 2018-12, with the labels that each got.

#1511 feat(TDP-3295): combine columns
  dataprep-api/src/main/java/org/talend/dataprep/api/service/TransformAPI.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/command/transformation/MultiColumnsActions.java
  dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
  dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/ReorderStepsUtils.java
  dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/ReorderStepsUtilsTest.java
  dataprep-test-api/src/test/resources/data/10L3C_ConcatColumns.csv
  dataprep-test-api/src/test/resources/data/10L3C_copy.csv
  dataprep-test-api/src/test/resources/features/ConcatColumnsActionTest.feature
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java
  dataprep-webapp/src/app/components/datagrid/header/datagrid-header-controller.spec.js
  dataprep-webapp/src/app/components/datagrid/services/datagrid-external-service.js
  dataprep-webapp/src/app/components/datagrid/services/datagrid-external-service.spec.js
  dataprep-webapp/src/app/components/recipe/recipe-component.spec.js
  dataprep-webapp/src/app/components/recipe/recipe-controller.js
  dataprep-webapp/src/app/components/recipe/recipe-controller.spec.js
  dataprep-webapp/src/app/components/recipe/step-description/step-description-controller.js
  dataprep-webapp/src/app/components/recipe/step-description/step-description-controller.spec.js
  dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/tab-item/tab-item-controller.js
  dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/tab-item/tab-item-directive.js
  dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/tab-item/tab-item.html
  dataprep-webapp/src/app/services/early-preview/early-preview-service.js
  dataprep-webapp/src/app/services/early-preview/early-preview-service.spec.js
  dataprep-webapp/src/app/services/playground/playground-service.js
  dataprep-webapp/src/app/services/playground/playground-service.spec.js
  dataprep-webapp/src/app/services/transformation/transformation-rest-service.js
  dataprep-webapp/src/app/services/transformation/transformation-service.js
  dataprep-webapp/src/app/services/transformation/transformation-service.spec.js
  dataprep-webapp/src/i18n/en.json
  dataprep-webapp/src/i18n/fr.json
Labels: backend, frontend, need review

#1789 fix(TDP-6349) : TI fails in CI
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ActionStep.java
Labels: integration tests, need review

#1792 chore: upgrade talend/ui to 1.9.0
  dataprep-webapp/package.json
  dataprep-webapp/yarn.lock
Labels: frontend, need review

#1786 fix(TDP-6388): remove findbugs and cleanup
  dataprep-api/src/test/java/org/talend/dataprep/api/service/TransformAPITest.java
  dataprep-api/src/test/java/org/talend/dataprep/api/service/test/APIClientTest.java
  dataprep-api/src/test/java/org/talend/dataprep/helper/api/ActionParamEnum.java
  dataprep-avro-message/pom.xml
  dataprep-backend-service/pom.xml
  dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/DataCatalogClient.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/io/ReleasableInputStream.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/store/metadata/DataSetMetadataRepository.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/store/metadata/memory/InMemoryDataSetMetadataRepository.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/FeatureContext.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/export/ExportParamAnalyzer.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/export/ExportType.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/folder/FolderUtil.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/folder/OSFolderUtil.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/TransformerFactory.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/TransformationServiceTest.java
Labels: backend, need review

#1769 chore(TDP-6356): remove redux-storage
  dataprep-webapp/src/app/configure.cmf.js
  dataprep-webapp/src/app/index.cmf.js
Labels: need review

#1795 chore: consistent wording
  dataprep-webapp/src/i18n/en.json
Labels: frontend, need review

#1798 chore: upgrade talend/ui to 1.9.1
  dataprep-webapp/package.json
  dataprep-webapp/yarn.lock
Labels: frontend, need review

#1797 feat(TDP-4993): hide dataset parameters for catalog
  dataprep-webapp/src/app/services/playground/playground-service.js
  dataprep-webapp/src/app/services/playground/playground-service.spec.js
  dataprep-webapp/src/app/settings/settings-service.js
  dataprep-webapp/src/app/settings/settings-service.spec.js
Labels: frontend, need review

#1791 feat(TDP-1680): Unable ConcatColumns TI
  dataprep-test-api/src/test/resources/features/ConcatColumnsActionTest.feature
Labels: backend, integration tests, need review

#1783 feat(TDP-5292): react cmf list preparations - part 1
  dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-container.scss
  dataprep-webapp/src/app/configure.cmf.js
  dataprep-webapp/src/app/next/actions/__tests__/__snapshots__/preparation.test.js.snap
  dataprep-webapp/src/app/next/actions/__tests__/preparation.test.js
  dataprep-webapp/src/app/next/actions/preparation.js
  dataprep-webapp/src/app/next/locales/en/tdp-cmf.json
  dataprep-webapp/src/app/next/locales/fr/tdp-cmf.json
  dataprep-webapp/src/app/next/locales/ja/tdp-cmf.json
  dataprep-webapp/src/app/next/sagas/effects/__tests__/folder.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/preparation.effects.mock.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/preparation.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/folder.effects.js
  dataprep-webapp/src/app/next/sagas/effects/preparation.effects.js
  dataprep-webapp/src/app/next/sagas/watchers/__tests__/folder.saga.test.js
  dataprep-webapp/src/app/next/sagas/watchers/__tests__/preparation.saga.test.js
  dataprep-webapp/src/app/next/sagas/watchers/folder.saga.js
  dataprep-webapp/src/app/next/sagas/watchers/index.js
  dataprep-webapp/src/app/next/sagas/watchers/preparation.saga.js
  dataprep-webapp/src/app/next/services/__tests__/preparation.service.mock.js
  dataprep-webapp/src/app/next/services/__tests__/preparation.service.test.js
  dataprep-webapp/src/app/next/services/preparation.service.js
  dataprep-webapp/src/app/next/settings/settings.json
Labels: Work in progress, enhancement, frontend
