Repository Talend/data-prep, pull requests merged in 2018-08, with the labels that each got.

#1532 fix(TDP-5961): fix fetch more
  dataprep-async-runtime/src/main/java/org/talend/dataprep/async/conditional/PreparationExportCondition.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/ApplyPreparationExportStrategy.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/CachedExportStrategy.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/PreparationExportStrategy.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/configuration/StandardExportStrategiesIntegrationTest.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/export/CachedExportStrategyTest.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/export/PreparationExportStrategyTest.java
Labels: backend, bug, need review

#1518 feat(TDP-5768): React 16
  dataprep-webapp/config/webpack.config.js
  dataprep-webapp/package.json
  dataprep-webapp/test-setup.js
  dataprep-webapp/yarn.lock
Labels: frontend, need review

#1537 fix: downgrade cmf plugin to save the build
  dataprep-webapp/package.json
  dataprep-webapp/yarn.lock
Labels: frontend, need review

#1539 fix(TDP-5908): fix out of memory in xlsx loading
  dataprep-backend-service/src/main/java/org/talend/dataprep/schema/xls/streaming/StreamingSheetReader.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/schema/xls/streaming/StreamingWorkbookReader.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/schema/xls/streaming/StreamingSheetTest.java
Labels: backend, bug, need review

#1540 fix(TDQ-15371): recognized patterns more precise
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/DateParserTest.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/quality/AnalyzerService.java
Labels: wait for another PR

#1541 feat(TDP-5987): Manage infinity values in dataSet cells
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/statistics/number/StreamNumberHistogramStatistics.java
  dataprep-backend-common/src/test/java/org/talend/dataprep/api/dataset/statistics/number/StreamNumberHistogramStatisticsTest.java
  dataprep-webapp/src/app/services/statistics/statistics-service.js
  dataprep-webapp/yarn.lock
Labels: backend, bug, frontend, need review

#1544 feat(TDQ-14160): add asian patterns
  dataprep-backend-common/src/main/java/org/talend/dataprep/quality/AnalyzerService.java
Labels: wait for another PR

#1543 feat(TDP-5987): Manage infinity values in dataSet cells
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/statistics/number/StreamNumberHistogramStatistics.java
  dataprep-backend-common/src/test/java/org/talend/dataprep/api/dataset/statistics/number/StreamNumberHistogramStatisticsTest.java
  dataprep-webapp/src/app/services/statistics/statistics-service.js
  dataprep-webapp/yarn.lock
Labels: backend, bug, frontend, need review

#1545 fix(TDP-5987) manage infinity values in data set cells 2 5
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/statistics/number/StreamNumberHistogramStatistics.java
  dataprep-backend-common/src/test/java/org/talend/dataprep/api/dataset/statistics/number/StreamNumberHistogramStatisticsTest.java
  dataprep-webapp/src/app/services/statistics/statistics-service.js
  dataprep-webapp/yarn.lock
Labels: backend, bug, frontend, need review

#1546 fix(TDP-5871) : Rework on how IT set execution context
  dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
  dataprep-test-api/src/test/resources/application.properties
Labels: enhancement, integration tests, need review

#1547 fix(TDQ-15598): incorrect custom date patterns are not recognized anymore
  dataprep-test-api/src/test/resources/data/best_sad_songs_exported.csv
  dataprep-test-api/src/test/resources/features/TrimActionTest.feature
Labels: backend, integration tests

#1549 chore(Integration tests): remove unused code regarding old filters implementation
  dataprep-api/src/test/java/org/talend/dataprep/helper/api/ActionFilterEnum.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/OSIntegrationTestUtil.java
Labels: backend, integration tests, need review, reviewing

#1516 fix(TDP-5885): getMetadata is not needed when no record
  dataprep-webapp/src/app/components/datagrid/message/datagrid-message-component.spec.js
  dataprep-webapp/src/app/components/datagrid/message/datagrid-message.html
  dataprep-webapp/src/app/services/playground/playground-service.js
  dataprep-webapp/src/app/services/playground/playground-service.spec.js
  dataprep-webapp/src/i18n/en.json
  dataprep-webapp/src/i18n/fr.json
Labels: frontend, need review

#1513 chore(TDP-5280): cmf breadcrumb
  dataprep-api/src/main/java/org/talend/dataprep/api/service/FolderAPI.java
  dataprep-webapp/package.json
  dataprep-webapp/src/app/components/widgets-containers/app-header-bar/app-header-bar-container.spec.js
  dataprep-webapp/src/app/configure.cmf.js
  dataprep-webapp/src/app/index-module.js
  dataprep-webapp/src/app/next/actions/__tests__/preparation.test.js
  dataprep-webapp/src/app/next/actions/preparation.js
  dataprep-webapp/src/app/next/components/App.container.js
  dataprep-webapp/src/app/next/components/__snapshots__/App.container.test.js.snap
  dataprep-webapp/src/app/next/sagas/effects/__tests__/notification.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/preparation.effects.mock.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/preparation.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/preparation.effects.js
  dataprep-webapp/src/app/next/sagas/watchers/__tests__/preparation.saga.test.js
  dataprep-webapp/src/app/next/sagas/watchers/preparation.saga.js
  dataprep-webapp/src/app/next/services/__tests__/preparation.service.mock.js
  dataprep-webapp/src/app/next/services/__tests__/preparation.service.test.js
  dataprep-webapp/src/app/next/services/preparation.service.js
  dataprep-webapp/src/settings/settings.json
  dataprep-webapp/yarn.lock
Labels: frontend, need review

#1534 feat(TDP-5966): add country converter
  dataprep-actions/pom.xml
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/conversions/CountryConverter.java
  dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
  dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages_fr.properties
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/conversions/CountryConverterTest.java
  dataprep-actions/src/test/resources/org/talend/dataprep/transformation/actions/conversions/countryConverterAction.json
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/suggestion/rules/BasicRules.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/suggestion/rules/TypeDomainRules.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/api/transformer/suggestion/SimpleSuggestionEngineTest.java
Labels: backend, need review

#1542 feat(tdp-5690) ti checks async
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/dto/ContentMetadata.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/dto/ContentMetadataColumn.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/dto/DatasetMeta.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/dto/Histogram.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/dto/Statistics.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/FilterStep.java
  dataprep-test-api/src/test/resources/data/10L3C_initial_quality.json
  dataprep-test-api/src/test/resources/data/10L3C_records.json
  dataprep-test-api/src/test/resources/features/DeleteAllEmptyColumnsAction.feature
  dataprep-test-api/src/test/resources/features/Filter.feature
  dataprep-test-api/src/test/resources/features/SampleRowCount.feature
  dataprep-test-api/src/test/resources/features/SmokeTest.feature
Labels: integration tests, need review

#1557 chore(files streams): fix failing unit tests on windows
  dataprep-backend-service/src/main/java/org/talend/dataprep/folder/store/file/FileSystemFolderRepository.java
  dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
  dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/PreparationServiceTest.java
Labels: backend, bug, need review, reviewing

#1559 fix(TDP-6011): button forms
  dataprep-webapp/src/app/components/widgets-containers/widgets-containers-module.js
Labels: frontend, need review

#1550 fix(TDP-6010): fix bug preventing from disabling all prep steps
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ActionStep.java
  dataprep-test-api/src/test/resources/data/8L3C_records.json
  dataprep-test-api/src/test/resources/features/StepsManipulation.feature
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/BaseExportStrategy.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/OptimizedExportStrategy.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/configuration/StandardExportStrategiesIntegrationTest.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/export/OptimizedExportStrategyTest.java
Labels: backend, bug, need review, reviewing

#1560 feat(TDP-5685): stop hiding current dataset in lookup list
  dataprep-api/src/main/java/org/talend/dataprep/api/service/DataSetAPI.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/command/transformation/SuggestLookupActions.java
  dataprep-api/src/test/java/org/talend/dataprep/api/service/DataSetAPITest.java
  dataprep-webapp/src/app/services/lookup/lookup-service.js
Labels: backend, need review

#1562 feat(TDP-5293): CMF i18n
  dataprep-webapp/cmf.json
  dataprep-webapp/package.json
  dataprep-webapp/src/app/configure.cmf.js
  dataprep-webapp/src/app/i18n.js
  dataprep-webapp/src/app/index-module.js
  dataprep-webapp/src/app/next/constants/i18n.js
  dataprep-webapp/src/app/next/constants/search.js
  dataprep-webapp/src/app/next/locales/en/data-prep-cmf.json
  dataprep-webapp/src/app/next/locales/en/tdp-app.json
  dataprep-webapp/src/app/next/locales/en/tdp-cmf.json
  dataprep-webapp/src/app/next/locales/en/tui-components.json
  dataprep-webapp/src/app/next/locales/en/tui-containers.json
  dataprep-webapp/src/app/next/locales/en/tui-forms.json
  dataprep-webapp/src/app/next/locales/fr/data-prep-cmf.json
  dataprep-webapp/src/app/next/locales/fr/tdp-app.json
  dataprep-webapp/src/app/next/locales/fr/tdp-cmf.json
  dataprep-webapp/src/app/next/locales/fr/tui-components.json
  dataprep-webapp/src/app/next/locales/fr/tui-containers.json
  dataprep-webapp/src/app/next/locales/fr/tui-forms.json
  dataprep-webapp/src/app/next/locales/index.js
  dataprep-webapp/src/app/next/locales/ja/tdp-app.json
  dataprep-webapp/src/app/next/locales/ja/tdp-cmf.json
  dataprep-webapp/src/app/next/locales/ja/tui-components.json
  dataprep-webapp/src/app/next/locales/ja/tui-containers.json
  dataprep-webapp/src/app/next/locales/ja/tui-forms.json
  dataprep-webapp/src/app/next/sagas/effects/__tests__/bootstrap.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/bootstrap.effects.js
  dataprep-webapp/src/app/next/sagas/watchers/__tests__/bootstrap.saga.test.js
  dataprep-webapp/src/app/next/sagas/watchers/bootstrap.saga.js
  dataprep-webapp/src/app/next/services/preparation.service.js
  dataprep-webapp/src/app/next/services/search-providers/dataprep.provider.js
  dataprep-webapp/src/app/next/services/search-providers/documentation.provider.js
  dataprep-webapp/src/app/next/settings/routes.json
  dataprep-webapp/src/app/next/settings/settings.json
  dataprep-webapp/yarn.lock
Labels: frontend, need review

#1381 chore(TDP-5285): react cmf copy move preparation
  dataprep-webapp/package.json
  dataprep-webapp/src/app/configure.cmf.js
  dataprep-webapp/src/app/i18n.js
  dataprep-webapp/src/app/next/actions/__tests__/__snapshots__/preparation.test.js.snap
  dataprep-webapp/src/app/next/actions/__tests__/preparation.test.js
  dataprep-webapp/src/app/next/actions/preparation.js
  dataprep-webapp/src/app/next/components/App.container.js
  dataprep-webapp/src/app/next/components/PreparationCopyMoveModal/PreparationCopyMoveModal.component.js
  dataprep-webapp/src/app/next/components/PreparationCopyMoveModal/PreparationCopyMoveModal.connect.js
  dataprep-webapp/src/app/next/components/PreparationCopyMoveModal/PreparationCopyMoveModal.scss
  dataprep-webapp/src/app/next/components/PreparationCopyMoveModal/index.js
  dataprep-webapp/src/app/next/components/PreparationCreatorModal/PreparationCreatorModal.component.js
  dataprep-webapp/src/app/next/components/PreparationCreatorModal/PreparationCreatorModal.connect.js
  dataprep-webapp/src/app/next/components/PreparationCreatorModal/index.js
  dataprep-webapp/src/app/next/components/__snapshots__/App.container.test.js.snap
  dataprep-webapp/src/app/next/components/index.js
  dataprep-webapp/src/app/next/constants/actions.js
  dataprep-webapp/src/app/next/locales/en/tdp-app.json
  dataprep-webapp/src/app/next/locales/en/tdp-cmf.json
  dataprep-webapp/src/app/next/locales/en/tui-components.json
  dataprep-webapp/src/app/next/locales/fr/tdp-app.json
  dataprep-webapp/src/app/next/locales/fr/tdp-cmf.json
  dataprep-webapp/src/app/next/locales/fr/tui-components.json
  dataprep-webapp/src/app/next/locales/ja/tdp-app.json
  dataprep-webapp/src/app/next/locales/ja/tdp-cmf.json
  dataprep-webapp/src/app/next/locales/ja/tui-components.json
  dataprep-webapp/src/app/next/sagas/effects/__tests__/preparation.effects.mock.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/preparation.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/preparation.effects.js
  dataprep-webapp/src/app/next/sagas/watchers/__tests__/preparation.saga.test.js
  dataprep-webapp/src/app/next/sagas/watchers/preparation.saga.js
  dataprep-webapp/src/app/next/services/__tests__/preparation.service.mock.js
  dataprep-webapp/src/app/next/services/__tests__/preparation.service.test.js
  dataprep-webapp/src/app/next/services/preparation.service.js
  dataprep-webapp/src/app/next/settings/settings.json
  dataprep-webapp/yarn.lock
Labels: Work in progress

#1567 chore: update display version for master
  dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties
Labels: enhancement, need review

#1566 fix(TDP-6016): fix styles in playground
  dataprep-webapp/src/app/components/filter/monitor/filter-monitor.html
  dataprep-webapp/src/app/components/lookup/dataset/list/lookup-dataset-list.html
  dataprep-webapp/src/app/components/lookup/grid/header/_lookup-datagrid-header.scss
  dataprep-webapp/src/app/components/suggestions-stats/stats-details/_stats-details.scss
  dataprep-webapp/src/app/components/widgets/modal/_modal.scss
  dataprep-webapp/src/app/components/widgets/modal/modal.html
Labels: frontend, need review

#1556 fix(TDP-5280): CMF - Browser back button management
  dataprep-webapp/src/app/next/sagas/effects/__tests__/bootstrap.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/preparation.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/bootstrap.effects.js
  dataprep-webapp/src/app/next/sagas/effects/preparation.effects.js
  dataprep-webapp/src/app/next/sagas/watchers/__tests__/bootstrap.saga.test.js
  dataprep-webapp/src/app/next/sagas/watchers/__tests__/preparation.saga.test.js
  dataprep-webapp/src/app/next/sagas/watchers/bootstrap.saga.js
  dataprep-webapp/src/app/next/sagas/watchers/preparation.saga.js
Labels: frontend, need review

#1568 fix(TDP-6016): styles in playground
  dataprep-webapp/src/app/components/widgets/modal/_modal.scss
Labels: frontend, need review

#1563 chore(TDP-5227): review the about dialog
  dataprep-webapp/src/app/configure.cmf.js
  dataprep-webapp/src/app/i18n.js
  dataprep-webapp/src/app/index-module.js
  dataprep-webapp/src/app/next/actions/__tests__/__snapshots__/version.test.js.snap
  dataprep-webapp/src/app/next/actions/__tests__/version.test.js
  dataprep-webapp/src/app/next/actions/help.js
  dataprep-webapp/src/app/next/actions/index.js
  dataprep-webapp/src/app/next/actions/version.js
  dataprep-webapp/src/app/next/components/AboutModal/AboutModal.component.js
  dataprep-webapp/src/app/next/components/AboutModal/AboutModal.component.test.js
  dataprep-webapp/src/app/next/components/AboutModal/AboutModal.connect.js
  dataprep-webapp/src/app/next/components/AboutModal/AboutModal.scss
  dataprep-webapp/src/app/next/components/AboutModal/__snapshots__/AboutModal.component.test.js.snap
  dataprep-webapp/src/app/next/components/App.container.js
  dataprep-webapp/src/app/next/components/Version/Version.component.js
  dataprep-webapp/src/app/next/components/Version/Version.connect.js
  dataprep-webapp/src/app/next/components/Version/index.js
  dataprep-webapp/src/app/next/components/index.js
  dataprep-webapp/src/app/next/locales/en/tdp-app.json
  dataprep-webapp/src/app/next/locales/fr/tdp-app.json
  dataprep-webapp/src/app/next/locales/ja/tdp-app.json
  dataprep-webapp/src/app/next/sagas/effects/__tests__/help.effects.mock.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/help.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/preparation.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/help.effects.js
  dataprep-webapp/src/app/next/sagas/watchers/__tests__/preparation.saga.test.js
  dataprep-webapp/src/app/next/sagas/watchers/preparation.saga.js
  dataprep-webapp/src/app/next/settings/settings.json
Labels: frontend, need review

#1565 fix(TDP-4346): second fetch more not working
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/ApplyPreparationExportStrategy.java
Labels: backend, bug, need review

#1572 fic(TDP-5860): async pb on dynamic params
  dataprep-api/src/main/java/org/talend/dataprep/api/service/TransformAPI.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/command/common/AsyncGet.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/command/preparation/DiffMetadata.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/command/preparation/PreparationGetContent.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/command/preparation/PreparationGetMetadata.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/command/preparation/PreviewAbstract.java
  dataprep-api/src/test/java/org/talend/dataprep/api/service/TransformAPITest.java
  dataprep-api/src/test/java/org/talend/dataprep/api/service/test/APIClientTest.java
  dataprep-async-runtime/src/main/java/org/talend/dataprep/async/AsyncAspect.java
  dataprep-async-runtime/src/main/java/org/talend/dataprep/async/AsyncController.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/command/GenericCommand.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java
Labels: backend, bug, need review

#1554 fix(TDP-5968/TDP-5999): Alternate implementation of migration
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/preparation/Preparation.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/preparation/PreparationDTO.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/preparation/store/PersistentPreparation.java
  dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
  dataprep-upgrade-common/src/main/java/org/talend/dataprep/upgrade/UpgradeService.java
Labels: need review

#1580 fix(export): do not close dataset stream too early
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/ApplyPreparationExportStrategy.java
Labels: backend, bug

#1573 feat(TDP-5966) : fix country converter
  dataprep-actions/pom.xml
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/conversions/CountryConverter.java
  dataprep-actions/src/main/resources/org/talend/dataprep/transformation/actions/conversions/country-codes.csv
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/ActionMetadataTestUtils.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/conversions/CountryConverterTest.java
  dataprep-actions/src/test/resources/org/talend/dataprep/transformation/actions/conversions/countryConverterAction.json
Labels: backend, need review, reviewing

#1574 feat(TDP-5293): React i18n
  dataprep-webapp/package.json
  dataprep-webapp/src/app/configure.cmf.js
  dataprep-webapp/src/app/i18n.js
  dataprep-webapp/src/app/next/actions/index.js
  dataprep-webapp/src/app/next/components/App.container.js
  dataprep-webapp/src/app/next/constants/search.js
  dataprep-webapp/src/app/next/locales/en/tui-components.json
  dataprep-webapp/src/app/next/locales/en/tui-containers.json
  dataprep-webapp/src/app/next/locales/en/tui-forms.json
  dataprep-webapp/src/app/next/locales/fr/tui-components.json
  dataprep-webapp/src/app/next/locales/fr/tui-containers.json
  dataprep-webapp/src/app/next/locales/ja/tdp-app.json
  dataprep-webapp/src/app/next/locales/ja/tdp-cmf.json
  dataprep-webapp/src/app/next/locales/ja/tui-components.json
  dataprep-webapp/src/app/next/locales/ja/tui-containers.json
  dataprep-webapp/src/app/next/sagas/effects/__tests__/bootstrap.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/search.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/bootstrap.effects.js
  dataprep-webapp/src/app/next/sagas/effects/http.effects.js
  dataprep-webapp/src/app/next/sagas/effects/preparation.effects.js
  dataprep-webapp/src/app/next/sagas/effects/search.effects.js
  dataprep-webapp/src/app/next/sagas/watchers/__tests__/redirect.saga.test.js
  dataprep-webapp/src/app/next/sagas/watchers/bootstrap.saga.js
  dataprep-webapp/src/app/next/services/search-providers/__tests__/documentation.provider.test.js
  dataprep-webapp/src/app/next/services/search-providers/documentation.provider.js
  dataprep-webapp/src/app/next/services/search.service.js
  dataprep-webapp/src/app/next/services/settings.service.js
  dataprep-webapp/src/app/next/settings/settings.json
  dataprep-webapp/yarn.lock
Labels: frontend, need review
