Repository Talend/data-prep, pull requests merged in 2018-06, with the labels that each got.

#1356 feat(TDP-5278): react-cmf search
  dataprep-webapp/src/app/configure.cmf.js
  dataprep-webapp/src/app/next/actions/dataset.js
  dataprep-webapp/src/app/next/actions/index.js
  dataprep-webapp/src/app/next/actions/preparation.js
  dataprep-webapp/src/app/next/actions/search.js
  dataprep-webapp/src/app/next/constants/actions.js
  dataprep-webapp/src/app/next/constants/index.js
  dataprep-webapp/src/app/next/constants/search.js
  dataprep-webapp/src/app/next/sagas/effects/search.effects.js
  dataprep-webapp/src/app/next/sagas/watchers/index.js
  dataprep-webapp/src/app/next/sagas/watchers/search.saga.js
  dataprep-webapp/src/app/next/sagas/watchers/search.saga.test.js
  dataprep-webapp/src/app/next/services/search-providers/dataprep.provider.js
  dataprep-webapp/src/app/next/services/search-providers/documentation.provider.js
  dataprep-webapp/src/app/next/services/search-providers/index.js
  dataprep-webapp/src/app/next/services/search-providers/search.provider.js
  dataprep-webapp/src/app/next/services/search.service.js
  dataprep-webapp/src/settings/settings.json
Labels: frontend, need review

#1364 feat(TDP-5726): Hash data
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/datamasking/HashData.java
  dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
  dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages_fr.properties
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/datamasking/HashDataTest.java
  dataprep-actions/src/test/resources/org/talend/dataprep/transformation/actions/datamasking/hashdata.json
Labels: backend, need review

#1363 fix(TDP-5639): Hide filter count when previewing
  dataprep-webapp/src/app/components/filter/bar/filter-bar-directive.js
  dataprep-webapp/src/app/components/filter/bar/filter-bar.html
  dataprep-webapp/src/app/components/filter/monitor/_filter-monitor.scss
  dataprep-webapp/src/app/components/filter/monitor/filter-monitor-directive.js
  dataprep-webapp/src/app/components/filter/monitor/filter-monitor-directive.spec.js
  dataprep-webapp/src/app/components/filter/monitor/filter-monitor.html
Labels: frontend, need review

#1365 feat(TDP-5575) : Make the multitenant users for IT configurable. (#925)
  dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
  dataprep-test-api/pom.xml
  dataprep-test-api/src/main/resources/application.properties
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/OSRunnerConfigurationIT.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/DataPrepStep.java
  dataprep-test-api/src/test/resources/application.properties
  dataprep-test-api/src/test/resources/logback.xml
Labels: enhancement, integration tests, need review

#1350 bug(TDP-4499) : dataset edition wirth wrong key
  dataprep-backend-common/src/test/java/org/talend/dataprep/api/dataset/json/DataSetRowIteratorTest.java
  dataprep-backend-common/src/test/resources/org/talend/dataprep/api/dataset/json/TCOMPContent_cache_serialized
  dataprep-backend-common/src/test/resources/org/talend/dataprep/api/dataset/json/dataset-sample_cache.json
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/analysis/asynchronous/BackgroundAnalysis.java
  dataprep-webapp/src/app/components/dataset/import/dataset-import.controller.js
Labels: backend, frontend, need review

#1369 fix(TDP-5726): fix section
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/datamasking/HashData.java
Labels: backend, need review

#1370 fix(TDP-5726): correct HashData action TU
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/datamasking/HashDataTest.java
Labels: backend, need review

#1367 chore(TDP-5741): improve cmf code coverage
  dataprep-webapp/.eslintrc
  dataprep-webapp/src/app/next/actions/__tests__/__snapshots__/dataset.test.js.snap
  dataprep-webapp/src/app/next/actions/__tests__/__snapshots__/folder.test.js.snap
  dataprep-webapp/src/app/next/actions/__tests__/__snapshots__/help.test.js.snap
  dataprep-webapp/src/app/next/actions/__tests__/__snapshots__/preparation.test.js.snap
  dataprep-webapp/src/app/next/actions/__tests__/__snapshots__/redirect.test.js.snap
  dataprep-webapp/src/app/next/actions/__tests__/__snapshots__/search.test.js.snap
  dataprep-webapp/src/app/next/actions/__tests__/__snapshots__/version.test.js.snap
  dataprep-webapp/src/app/next/actions/__tests__/dataset.test.js
  dataprep-webapp/src/app/next/actions/__tests__/folder.test.js
  dataprep-webapp/src/app/next/actions/__tests__/help.test.js
  dataprep-webapp/src/app/next/actions/__tests__/preparation.test.js
  dataprep-webapp/src/app/next/actions/__tests__/redirect.test.js
  dataprep-webapp/src/app/next/actions/__tests__/search.test.js
  dataprep-webapp/src/app/next/actions/__tests__/version.test.js
  dataprep-webapp/src/app/next/actions/preparation.js
  dataprep-webapp/src/app/next/actions/version.js
  dataprep-webapp/src/app/next/constants/search.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/bootstrap.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/help.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/http.effects.mock.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/http.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/preparation.effects.mock.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/preparation.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/redirect.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/search.effects.mock.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/search.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/preparation.effects.js
  dataprep-webapp/src/app/next/sagas/effects/search.effects.js
  dataprep-webapp/src/app/next/sagas/watchers/__tests__/bootstrap.saga.test.js
  dataprep-webapp/src/app/next/sagas/watchers/__tests__/help.saga.test.js
  dataprep-webapp/src/app/next/sagas/watchers/__tests__/http.saga.test.js
  dataprep-webapp/src/app/next/sagas/watchers/__tests__/preparation.saga.test.js
  dataprep-webapp/src/app/next/sagas/watchers/__tests__/redirect.saga.test.js
  dataprep-webapp/src/app/next/sagas/watchers/__tests__/search.saga.test.js
  dataprep-webapp/src/app/next/sagas/watchers/http.saga.test.js
  dataprep-webapp/src/app/next/sagas/watchers/search.saga.js
  dataprep-webapp/src/app/next/sagas/watchers/search.saga.test.js
  dataprep-webapp/src/app/next/services/__tests__/preparation.service.mock.js
  dataprep-webapp/src/app/next/services/__tests__/preparation.service.test.js
  dataprep-webapp/src/app/next/services/__tests__/search.service.test.js
  dataprep-webapp/src/app/next/services/preparation.service.js
  dataprep-webapp/src/app/next/services/search-providers/__tests__/dataprep.provider.mock.js
  dataprep-webapp/src/app/next/services/search-providers/__tests__/dataprep.provider.test.js
  dataprep-webapp/src/app/next/services/search-providers/__tests__/documentation.provider.mock.js
  dataprep-webapp/src/app/next/services/search-providers/__tests__/documentation.provider.test.js
  dataprep-webapp/src/app/next/services/search-providers/__tests__/search.provider.test.js
  dataprep-webapp/src/app/next/services/search-providers/documentation.provider.js
  dataprep-webapp/test-setup.js
Labels: enhancement, frontend, need review

#1372 chore: assert that effects ends and watchers loops
  dataprep-webapp/src/app/next/sagas/effects/__tests__/bootstrap.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/preparation.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/redirect.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/search.effects.test.js
  dataprep-webapp/src/app/next/sagas/watchers/__tests__/bootstrap.saga.test.js
  dataprep-webapp/src/app/next/sagas/watchers/__tests__/help.saga.test.js
  dataprep-webapp/src/app/next/sagas/watchers/__tests__/preparation.saga.test.js
  dataprep-webapp/src/app/next/sagas/watchers/__tests__/search.saga.test.js
Labels: Work in progress, enhancement, frontend

#1374 chore: fix CI build and notifications
  dataprep-webapp/package.json
  dataprep-webapp/yarn.lock
Labels: frontend, need review

#1376 fix(TDP-5726): fix hash action
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/datamasking/HashData.java
  dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/datamasking/HashDataTest.java
Labels: backend, need review

#1375 fix(TDP-5769): unable to overwrite an existing dataset
  dataprep-webapp/src/app/services/dataset/rest/dataset-rest-service.js
  dataprep-webapp/src/app/services/dataset/rest/dataset-rest-service.spec.js
Labels: bug, frontend, need review

#1382 fix(TDP-5773): no more circular spinner on the step progress modal
  dataprep-webapp/src/app/components/step-progress/step-progress.html
Labels: bug, frontend

#1378 fix(TDP-4499): edit salesforce dataset with key changed
  dataprep-backend-common/src/test/java/org/talend/dataprep/api/dataset/json/DataSetRowIteratorTest.java
  dataprep-backend-common/src/test/resources/org/talend/dataprep/api/dataset/json/TCOMPContent_cache_serialized
  dataprep-backend-common/src/test/resources/org/talend/dataprep/api/dataset/json/dataset-sample_cache.json
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/analysis/asynchronous/BackgroundAnalysis.java
  dataprep-webapp/src/app/components/dataset/import/dataset-import.controller.js
Labels: backend, bug, frontend, need review

#1301 wi(TDP-5616): handle http 202's status NEW
  dataprep-webapp/src/app/services/rest/rest-queued-message-interceptor-factory.js
Labels: bug, frontend

#1384 fix(TDP-5743) : Fix priority 1 unstable Integration Test features
  dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
Labels: integration tests, need review

#1385 fix(5771): Update spring cloud version to Dalston.SR4
  dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties
  dataprep-backend/pom.xml
Labels: backend, need review

#1390 fix(TDP-5790): content is loaded twice when loading a preparation
  dataprep-webapp/src/app/services/playground/playground-service.js
Labels: bug, frontend, need review

#1387 wi(TDP-5776): handle http 202's status FAILED
  dataprep-webapp/.eslintrc
  dataprep-webapp/src/app/services/rest/rest-queued-message-interceptor-factory.js
Labels: bug, frontend, need review

#1392 feat(TDP-5743) : Fix priority 1 unstable Integration Test features
  dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
  dataprep-api/src/test/java/org/talend/dataprep/helper/api/ActionParamEnum.java
  dataprep-test-api/README.md
  dataprep-test-api/pom.xml
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/BackendProperties.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/DataPrepStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/FeatureContext.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/GlobalStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/User.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ActionStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ExportPreparationStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/FolderStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/PreparationStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/export/AbstractExportSampleStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/export/ExportSampleStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/OSIntegrationTestUtil.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/OSIntegrationTestUtilTest.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/PreparationUID.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/export/ExportType.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/export/ExportUtil.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/folder/FolderUtil.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/folder/OSFolderUtil.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/folder/OSFolderUtilTest.java
  dataprep-test-api/src/test/resources/features/Aggregation.feature
  dataprep-test-api/src/test/resources/features/ChangeDatePatternActionTest.feature
  dataprep-test-api/src/test/resources/features/DatasetCache.feature
  dataprep-test-api/src/test/resources/features/ExportFormat.feature
  dataprep-test-api/src/test/resources/features/ExportFormatXLSXResult.feature
  dataprep-test-api/src/test/resources/features/ExportPreparationFromCSV.feature
  dataprep-test-api/src/test/resources/features/ExportPreparationFromXLSX.feature
  dataprep-test-api/src/test/resources/features/PreparationContent.feature
  dataprep-test-api/src/test/resources/features/SearchAndReplaceActionTest.feature
  dataprep-test-api/src/test/resources/features/SmokeTest.feature
  dataprep-test-api/src/test/resources/features/SplitActionTest.feature
  dataprep-test-api/src/test/resources/features/TrimActionTest.feature
Labels: enhancement, integration tests, need review

#1397 fix(TDP-5795): details are loaded twice when loading a preparation
  dataprep-webapp/src/app/services/playground/playground-service.js
Labels: bug, frontend, need review

#1402 feat(TDP-4668) provide default zipkin configuration
  dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties
Labels: need review

#1389 chore: upgrade monorepo
  dataprep-webapp/package.json
  dataprep-webapp/pom.xml
  dataprep-webapp/src/app/components/history-control/history-control.html
  dataprep-webapp/src/app/components/playground/header/_playground-header.scss
  dataprep-webapp/src/app/components/playground/header/playground-header.html
  dataprep-webapp/src/app/components/widgets/editable-text/_editable-text.scss
  dataprep-webapp/src/app/next/components/__snapshots__/App.container.test.js.snap
  dataprep-webapp/yarn.lock
Labels: frontend, need review

#1411 chore: change list dataset return type to Stream
  dataprep-api/src/main/java/org/talend/dataprep/api/service/DataSetAPI.java
Labels: backend, bug, need review

#1405 chore: protect our connection pools by autoclosing DataSet
  dataprep-api/src/main/resources/application.properties
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/DataSet.java
  dataprep-dataset/src/main/resources/application.properties
  dataprep-preparation/src/main/resources/application.properties
  dataprep-preparation/src/test/resources/application.properties
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/DataSetExportStrategy.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/PreparationExportStrategy.java
  dataprep-transformation/src/main/resources/application.properties
Labels: Work in progress, backend, enhancement

#1413 fix(TDQ-14216): stream histogram statistics handle big decimal values
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/statistics/number/StreamNumberHistogramStatistics.java
  dataprep-backend-common/src/test/java/org/talend/dataprep/api/dataset/statistics/number/StreamNumberHistogramStatisticsTest.java
Labels: backend, bug, need review

#1418 Revert "wi(TDP-5776): handle http 202's status FAILED (#1387)"
  dataprep-webapp/.eslintrc
  dataprep-webapp/src/app/services/rest/rest-queued-message-interceptor-factory.js
Labels: need review

#1417 Revert "wi(TDP-5776): handle http 202's status FAILED (#1387)"
  dataprep-webapp/.eslintrc
  dataprep-webapp/src/app/services/rest/rest-queued-message-interceptor-factory.js
Labels: need review

#1393 fix(TDP-5733): fix empty column on fetch more
  dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/StepNodeTransformation.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/DataPrepStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/PreparationStep.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/BaseTransformationService.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/OptimizedExportStrategy.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/configuration/StandardExportStrategiesIntegrationTest.java
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/service/configuration/preparation_details.json
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/service/configuration/two_steps_preparation_details.json
Labels: backend, bug, reviewing

#1347 feat(TDP-4592): Generate sequence when create new column
  dataprep-actions/src/main/java/org/talend/dataprep/PreparationParser.java
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/column/CreateNewColumn.java
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/common/AbstractGenerateSequenceAction.java
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/fill/GenerateSequence.java
  dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
  dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages_fr.properties
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/column/CreateNewColumnTest.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/action/ActionDefinition.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/builder/ActionsStaticProfiler.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/builder/StatisticsNodesBuilder.java
  dataprep-preparation/src/main/java/org/talend/dataprep/preparation/configuration/PreparationConversions.java
  dataprep-test-api/src/test/resources/data/customers.csv
  dataprep-test-api/src/test/resources/data/customers_prep_exported.csv
  dataprep-test-api/src/test/resources/features/CreateNewColumnActionTest.feature
Labels: backend, need review, reviewing
