Repository Talend/data-prep, pull requests merged in 2018-02, with the labels that each got.

#1109 fix(TDP-4132): unwanted notifications
  dataprep-webapp/src/app/components/upgrade-version/upgrade-version-service.js
  dataprep-webapp/src/app/services/about/about-service.js
  dataprep-webapp/src/app/services/dataset/rest/dataset-rest-service.js
  dataprep-webapp/src/app/services/rest/rest-error-message-interceptor-factory.js
Labels: Merged build passed

#1107 TDP-5225 Migration task about creation new column toggle failed
  dataprep-backend-service/src/main/java/org/talend/dataprep/user/store/file/FileSystemUserDataRepository.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/user/store/inmemory/InMemoryUserDataRepository.java
  dataprep-upgrade-common/src/main/java/org/talend/dataprep/upgrade/common/ActionNewColumnToggleCommon.java
  dataprep-upgrade/src/test/java/org/talend/dataprep/upgrade/to_2_3_0_PE/MigrateActionsParametersTest.java
Labels: Merged build failed, backend, bug, need review

#1106 feat(TDP-4527): be able to activate theme (#1045)
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/AppSettings.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/context/api/ContextSettings.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/context/provider/ContextProvider.java
  dataprep-api/src/test/java/org/talend/dataprep/api/service/AppSettingsAPITest.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/ui/UiConfiguration.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/ui/UiPropertiesConfiguration.java
  dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties
  dataprep-webapp/config/sass.conf.js
  dataprep-webapp/config/webpack.config.js
  dataprep-webapp/package.json
  dataprep-webapp/src/app/components/app/app-directive.js
  dataprep-webapp/src/app/components/app/app-directive.spec.js
  dataprep-webapp/src/app/components/app/app-module.js
  dataprep-webapp/src/app/components/app/app.html
  dataprep-webapp/src/app/components/playground/header/playground-header.html
  dataprep-webapp/src/app/components/widgets-containers/app-header-bar/app-header-bar-controller.js
  dataprep-webapp/src/app/components/widgets-containers/layout/layout.html
  dataprep-webapp/src/app/components/widgets-containers/layout/layout.scss
  dataprep-webapp/src/app/css/utils/_colors.scss
  dataprep-webapp/src/app/index.scss
  dataprep-webapp/src/app/index.themed.scss
  dataprep-webapp/src/app/settings/settings-service.js
  dataprep-webapp/src/app/settings/settings-service.spec.js
  dataprep-webapp/src/mocks/Settings.mock.js
  dataprep-webapp/yarn.lock
Labels: Merged build failed

#1115 TDP-5225 Migration task about creation new column toggle failed
  dataprep-upgrade-common/src/main/java/org/talend/dataprep/upgrade/common/ActionNewColumnToggleCommon.java
  dataprep-upgrade/src/main/java/org/talend/dataprep/upgrade/to_2_3_0_PE/MigrateActionsParameters.java
  dataprep-upgrade/src/test/java/org/talend/dataprep/upgrade/to_2_3_0_PE/MigrateActionsParametersTest.java
Labels: backend, bug, need review

#1110 fix(TDP-5226): deal with non TDP users
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/AppSettingsConfigurer.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/configurer/HeaderbarHelpConfigurerForNonTDPUsers.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/CommonActionsProvider.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/WindowActions.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/views/provider/HomeViewsForNonTDPUsers.java
Labels: Merged build passed, backend

#1116 fix: Handle cases when preparation action id changes during migration
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/Cos.java
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/Exponential.java
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/Logarithm.java
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/Max.java
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/Min.java
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/NaturalLogarithm.java
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/Negate.java
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/Pow.java
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/Sin.java
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/SquareRoot.java
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/Tan.java
  dataprep-upgrade-common/src/main/java/org/talend/dataprep/upgrade/common/ActionNewColumnToggleCommon.java
  dataprep-upgrade-common/src/test/java/org/talend/dataprep/upgrade/common/ActionNewColumnToggleCommonTest.java
Labels: Merged build passed

#1121 fix(TDP-5225): Handle cases when preparation action id changes during migration
  dataprep-upgrade-common/src/main/java/org/talend/dataprep/upgrade/common/ActionNewColumnToggleCommon.java
  dataprep-upgrade-common/src/test/java/org/talend/dataprep/upgrade/common/ActionNewColumnToggleCommonTest.java
Labels: Merged build passed

#1122 Fix/fhuaulme/toggle migration fix root step
  dataprep-upgrade-common/src/test/java/org/talend/dataprep/upgrade/common/ActionNewColumnToggleCommonTest.java
Labels: Merged build failed

#1097 feat(TDP-5052): TI-create custom semantic type
  dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
  dataprep-api/src/test/java/org/talend/dataprep/helper/api/ActionParamEnum.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/FeatureContext.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/OSIntegrationTestUtil.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/export/ExportType.java
Labels: Merged build passed, backend, need review

#1125 fix(TDP-5249): split action - add retrocompatibility with old parameters
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/text/Split.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/text/SplitTest.java
  dataprep-actions/src/test/resources/org/talend/dataprep/transformation/actions/text/splitActionOldParam.json
Labels: Merged build passed, backend, bug, need review

#1128 fix(TDP-5256): Manage legacy Phone Format Number types
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/phonenumber/FormatPhoneNumber.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/phonenumber/FormatPhoneNumberTest.java
Labels: Merged build passed, backend, bug, need review

#1129 feat(TDP-5167): Update Data Quality libraries to 4.0.4-SNAPSHOT
  dataprep-backend/pom.xml
Labels: Merged build passed, Work in progress, backend

#1100 fix(TDP-3703): persistent actions style
  dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-container.scss
Labels: Merged build failed, frontend, need review

#1134 fix(TDP-5264): fix charts btn display
  dataprep-webapp/src/app/components/suggestions-stats/column-profile/_column-profile.scss
Labels: Merged build passed, bug, frontend, need review

#1137 fix(TDP-5253): fix convert date not applied after column duplication (migration to winter affected)
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/common/ActionsUtils.java
  dataprep-upgrade/src/test/java/org/talend/dataprep/upgrade/to_2_3_0_PE/MigrateActionsParametersTest.java
Labels: Merged build passed, backend, bug, need review

#1139 chore: Update DQ lib version
  dataprep-backend/pom.xml
Labels: Merged build passed

#1140 feat(TDP-5052): TI- Change cleanAfter order
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java
Labels: Merged build passed, backend, need review

#1142 fix(TDP-5247): fix default name for new column
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/column/CreateNewColumn.java
Labels: Merged build failed, backend, bug, need review

#1144 Aleboulanger/fix/tdp 5256 format phone number migration
  dataprep-upgrade/src/main/java/org/talend/dataprep/upgrade/to_2_3_0_PE/FormatPhoneNumberAction.java
  dataprep-upgrade/src/main/java/org/talend/dataprep/upgrade/to_2_3_0_PE/MigrateActionsParameters.java
  dataprep-upgrade/src/test/java/org/talend/dataprep/upgrade/to_2_3_0_PE/MigrateActionsParametersTest.java
  dataprep-upgrade/src/test/resources/snapshots/2.1.1-PE/store/datasets/metadata/54c9917f-4229-4e67-a7b7-a33ad7391f66
  dataprep-upgrade/src/test/resources/snapshots/2.1.1-PE/store/folders/preparation@98657d6f-620c-49f5-9476-1a4314aa8fcf
  dataprep-upgrade/src/test/resources/snapshots/2.1.1-PE/store/preparations/PersistentPreparation-98657d6f-620c-49f5-9476-1a4314aa8fcf
  dataprep-upgrade/src/test/resources/snapshots/2.1.1-PE/store/preparations/PersistentStep-37776a04-2805-4e83-a50d-29fbeab144e7
  dataprep-upgrade/src/test/resources/snapshots/2.1.1-PE/store/preparations/PersistentStep-3fa5b821-7dde-491d-a6fd-7a11ef18932f
  dataprep-upgrade/src/test/resources/snapshots/2.1.1-PE/store/preparations/PreparationActions-6cae9216b36b9cdbc05807109d84f420020a145e
  dataprep-upgrade/src/test/resources/snapshots/2.1.1-PE/store/preparations/PreparationActions-ac3b7cf52048dc8a5aaa27512a2c7e55b97c5fe4
  dataprep-upgrade/src/test/resources/snapshots/2.1.1-PE/store/preparations/StepRowMetadata-0738d08a-2b56-4376-92c1-5d50257474f1
  dataprep-upgrade/src/test/resources/snapshots/2.1.1-PE/store/preparations/StepRowMetadata-babf6d75-1237-4360-b53d-cf2cc0ba5e86
Labels: Merged build failed

#1146 fix(TDP-5256): Migration task for FormatPhoneNumber action
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/phonenumber/FormatPhoneNumber.java
  dataprep-upgrade-common/src/main/java/org/talend/dataprep/upgrade/common/ActionFormatPhoneNumber.java
  dataprep-upgrade/src/main/java/org/talend/dataprep/upgrade/to_2_3_0_PE/FormatPhoneNumberAction.java
Labels: Merged build passed, backend, bug, need review

#1147 fix/TDP-5247 Create new column don't set the constant value or value …
  dataprep-upgrade-common/src/main/java/org/talend/dataprep/upgrade/common/ActionCreateNewColumn.java
  dataprep-upgrade/src/main/java/org/talend/dataprep/upgrade/to_2_3_0_PE/MigrateActionsCreateNewColumn.java
Labels: Merged build passed, backend, bug, need review

#1149 fix(TDP-5256) format phone number migration task
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/phonenumber/FormatPhoneNumber.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/phonenumber/FormatPhoneNumberTest.java
  dataprep-upgrade-common/src/main/java/org/talend/dataprep/upgrade/common/ActionFormatPhoneNumber.java
  dataprep-upgrade/src/main/java/org/talend/dataprep/upgrade/to_2_3_0_PE/FormatPhoneNumberAction.java
Labels: Merged build passed, backend, bug, need review

#1148 fix(TDP-5273): add missing HEADERBAR_APPS label
  dataprep-webapp/src/i18n/en.json
  dataprep-webapp/src/i18n/fr.json
  dataprep-webapp/src/i18n/ja.json
Labels: Merged build passed, bug, frontend, need review

#1132 wi(TDP-5252): front ut cleanup
  dataprep-webapp/src/app/services/statistics/statistics-service.spec.js
Labels: Merged build passed, enhancement, frontend, need review

#1152 chore: version service fixes
  dataprep-backend-service/src/main/java/org/talend/dataprep/api/service/info/VersionService.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/api/service/info/VersionServiceTest.java
Labels: Merged build passed, backend, need review

#1095 fix(TDP-4926): bug change date format statistics
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/common/ActionsUtils.java
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/ChangeDatePattern.java
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/ComputeTimeSince.java
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/DateCalendarConverter.java
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/ExtractDateTokens.java
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/text/Trim.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/ActionMetadataTestUtils.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/ChangeDatePatternTest.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/ComputeTimeSinceTest.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/ExtractDateTokensTest.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/math/ExtractNumberTest.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/text/TrimTest.java
  dataprep-api/src/test/java/org/talend/dataprep/api/service/PreparationAPITest.java
  dataprep-api/src/test/java/org/talend/dataprep/helper/api/ActionParamEnum.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/ColumnMetadata.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/statistics/Quantiles.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/statistics/Statistics.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/statistics/TextLengthSummary.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/quality/AnalyzerService.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/Pipeline.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/StepNodeTransformation.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/StepNodeTransformer.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/builder/StatisticsNodesBuilder.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/node/StepNode.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/preparation/store/PersistentStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/FileStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/OSIntegrationTestUtil.java
  dataprep-test-api/src/test/resources/data/A-customers_100_with_pb.csv
  dataprep-test-api/src/test/resources/data/A-customers_100_with_pb_exported.csv
  dataprep-test-api/src/test/resources/data/A-customers_100_with_pb_exported_newCol.csv
  dataprep-test-api/src/test/resources/data/A-customers_100_with_pb_updated_exported_newCol.csv
  dataprep-test-api/src/test/resources/data/Albums_Musique.txt
  dataprep-test-api/src/test/resources/data/Albums_Musique_prep_exported.csv
  dataprep-test-api/src/test/resources/data/best_sad_songs_exported.csv
  dataprep-test-api/src/test/resources/data/best_sad_songs_of_all_time.csv
  dataprep-test-api/src/test/resources/data/best_sad_songs_search_exported.csv
  dataprep-test-api/src/test/resources/data/best_sad_songs_split_exported.csv
  dataprep-test-api/src/test/resources/features/ChangeDatePatternActionTest.feature
  dataprep-test-api/src/test/resources/features/SearchAndReplaceActionTest.feature
  dataprep-test-api/src/test/resources/features/SmokeTest.feature
  dataprep-test-api/src/test/resources/features/SplitActionTest.feature
  dataprep-test-api/src/test/resources/features/TrimActionTest.feature
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/json/PipelineTransformer.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/json/UpdatedStepVisitor.java
Labels: Merged build passed, backend, bug, need review

#1105 feat(TDP-5214): update OS integration tests
  dataprep-api/src/test/java/org/talend/dataprep/helper/api/Action.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/OSRunnerConfigurationTest.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ActionStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/OSIntegrationTestUtil.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/OSIntegrationTestUtilTest.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/folder/OSFolderUtil.java
  dataprep-test-api/src/test/resources/features/ChangeDatePatternActionTest.feature
  dataprep-test-api/src/test/resources/features/DatasetCache.feature
  dataprep-test-api/src/test/resources/features/ExportFormatXLSXResult.feature
  dataprep-test-api/src/test/resources/features/ExportPreparationFromCSV.feature
  dataprep-test-api/src/test/resources/features/ExportPreparationFromXLSX.feature
  dataprep-test-api/src/test/resources/features/SearchAndReplaceActionTest.feature
  dataprep-test-api/src/test/resources/features/SmokeTest.feature
  dataprep-test-api/src/test/resources/features/SplitActionTest.feature
  dataprep-test-api/src/test/resources/features/TrimActionTest.feature
Labels: Merged build passed, backend, need review
