Repository Talend/data-prep, pull requests merged in 2018-04, with the labels that each got.

#962 fix(TDP-4690): Review preparation cleaner
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/preparation/Step.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/preparation/store/ObjectPreparationRepository.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/preparation/store/PersistentPreparationRepository.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/preparation/store/PreparationRepository.java
  dataprep-maintenance/src/main/java/org/talend/dataprep/maintenance/preparation/OrphanStepsFinder.java
  dataprep-maintenance/src/main/java/org/talend/dataprep/maintenance/preparation/PreparationCleaner.java
  dataprep-maintenance/src/main/java/org/talend/dataprep/maintenance/preparation/PreparationOrphanStepsFinder.java
  dataprep-maintenance/src/main/java/org/talend/dataprep/maintenance/preparation/PreparationStepMarker.java
  dataprep-maintenance/src/main/java/org/talend/dataprep/maintenance/preparation/StepMarker.java
  dataprep-maintenance/src/test/java/org/talend/dataprep/maintenance/preparation/PreparationCleanerTest.java
  dataprep-maintenance/src/test/java/org/talend/dataprep/maintenance/preparation/PreparationOrphanStepsFinderTest.java
  dataprep-maintenance/src/test/java/org/talend/dataprep/maintenance/preparation/PreparationStepMarkerTest.java
Labels: backend, need review

#1236 fix(TDP-5444): close stream when body is converted (#1231)
  dataprep-backend-service/src/main/java/org/talend/dataprep/command/Defaults.java
Labels: backend, bug, need review

#1216 fix(TDP-5439) : IT tests failures (maintenance/2.3)
  dataprep-test-api/pom.xml
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/FeatureContext.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/GlobalStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/GlobalStepTest.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ExportPreparationStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/FolderStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/PreparationStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/folder/FolderUtil.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/folder/OSFolderUtil.java
  dataprep-test-api/src/test/resources/features/ExportFormat.feature
Labels: backend, integration tests, need review

#1237 fix(TDP-5123): allow non pattern-neutral CSV separator
  dataprep-backend-service/src/main/java/org/talend/dataprep/schema/csv/CSVFastHeaderAndTypeAnalyzer.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/schema/csv/CSVFastHeaderAndTypeAnalyzerTest.java
Labels: backend, bug, need review

#1240 fix(TDP-5439) : add fix from 2.3
  dataprep-test-api/pom.xml
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/FeatureContext.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/GlobalStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/GlobalStepTest.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ExportPreparationStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/FolderStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/PreparationStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/folder/FolderUtil.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/folder/OSFolderUtil.java
  dataprep-test-api/src/test/resources/features/ExportFormat.feature
Labels: reviewing

#1227 feat(TDP-5419): implement business requirements
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/api/ActionSettings.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/DatasetActions.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/InventoryActions.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/MenuActions.java
  dataprep-webapp/package.json
  dataprep-webapp/src/app/components/datagrid/header/datagrid-header.html
  dataprep-webapp/src/app/components/datagrid/index-header/datagrid-index-header.html
  dataprep-webapp/src/app/components/export/export.html
  dataprep-webapp/src/app/components/preparation/creator/form/preparation-creator-form.html
  dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list.html
  dataprep-webapp/src/app/components/suggestions-stats/stats-details/stats-details-controller.js
  dataprep-webapp/src/app/components/transformation/form/transformation-form.html
  dataprep-webapp/src/app/components/transformation/menu/transformation-menu.html
  dataprep-webapp/src/app/components/transformation/menu/type/type-transformation-menu.html
  dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-controller.js
  dataprep-webapp/src/app/components/widgets-containers/side-panel/side-panel-controller.js
  dataprep-webapp/src/app/components/widgets-containers/widgets-containers-module.js
  dataprep-webapp/src/app/components/widgets/editable-text/editable-text.html
  dataprep-webapp/src/app/components/widgets/quality-bar/quality-bar.html
  dataprep-webapp/src/app/services/dataset/list/dataset-list-service.js
  dataprep-webapp/src/app/services/dataset/list/dataset-list-service.spec.js
  dataprep-webapp/src/app/services/folder/folder-service.js
  dataprep-webapp/src/app/services/folder/folder-service.spec.js
  dataprep-webapp/src/app/services/inventory/inventory-module.js
  dataprep-webapp/src/app/services/inventory/list/inventory-list-service.js
  dataprep-webapp/src/app/services/inventory/list/inventory-list-service.spec.js
  dataprep-webapp/src/app/settings/settings-actions-service.js
  dataprep-webapp/src/app/settings/settings-actions-service.spec.js
  dataprep-webapp/yarn.lock
Labels: backend, frontend, need review

#1228 feature(TDP-5324): Delete Multi-Tenant (Integration tests on DQ dict …
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java
Labels: backend, need review, reviewing

#1251 fix(TDP-5419): move data-feature to label
  dataprep-webapp/src/app/components/transformation/menu/type/type-transformation-menu.html
Labels: frontend, need review

#1252 fix(TDP-5419): add category for functions
  dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list-controller.js
  dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list-controller.spec.js
  dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list.html
  dataprep-webapp/src/app/components/transformation/form/transformation-form-directive.js
  dataprep-webapp/src/app/components/transformation/form/transformation-form.html
Labels: frontend, need review

#1253 fix(TDP-5419): fix data attributes
  dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list.html
Labels: bug, frontend, need review

#1256 fix(TDP-5419): improve business requirements
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/action/ActionDefinition.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/action/ActionForm.java
  dataprep-backend-common/src/test/java/org/talend/dataprep/api/action/ActionFormTest.java
  dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list.html
Labels: backend, frontend, need review

#1259 fix(TDP-5419): fix tests
  dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list-controller.js
  dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list-controller.spec.js
  dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list.html
Labels: frontend, need review

#1247 fix(TDP-4959): unmanaged exceptions
  dataprep-api/src/main/java/org/talend/dataprep/api/service/command/preparation/PreparationCreate.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/command/preparation/PreparationGetContent.java
  dataprep-api/src/test/java/org/talend/dataprep/api/service/PreparationAPITest.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/api/export/ExportParametersUtil.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/command/dataset/DataSetGetMetadata.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/command/preparation/PreparationDetailsGet.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/exception/error/PreparationErrorCodes.java
Labels: backend, need review

#1254 fix(TDP-5439) : add missing EE part cleaner
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/DataPrepStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/GlobalStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ExportPreparationStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/folder/OSFolderUtil.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/folder/OSFolderUtilTest.java
  dataprep-test-api/src/test/resources/features/ChangeDatePatternActionTest.feature
  dataprep-test-api/src/test/resources/features/SplitActionTest.feature
Labels: backend, bug, integration tests, need review

#1263 wi(TDP-5419): update dq and ui libs to meet pendo needs
  dataprep-webapp/package.json
  dataprep-webapp/yarn.lock
Labels: frontend, need review

#1260 feat(TDP-5504): app loader
  dataprep-webapp/config/app.conf.js
  dataprep-webapp/config/webpack.config.js
  dataprep-webapp/package.json
  dataprep-webapp/src/app/components/playground/playground-directive.spec.js
  dataprep-webapp/src/app/components/playground/playground.html
  dataprep-webapp/src/app/components/widgets-containers/widgets-containers-module.js
  dataprep-webapp/src/app/index-module.js
  dataprep-webapp/src/app/services/playground/playground-service.js
  dataprep-webapp/src/app/services/playground/playground-service.spec.js
  dataprep-webapp/src/index.html
  dataprep-webapp/yarn.lock
Labels: frontend, need review

#1266 fix(TDP-5504): add app loader size bumping
  dataprep-webapp/package.json
  dataprep-webapp/yarn.lock
Labels: frontend, need review

#1268 fix(TDP-5447): Remove semantic type does not work on "change semantic domain" step
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/type/Type.java
Labels: backend, bug, need review, reviewing

#1272 fix: apploader icon
  dataprep-webapp/config/app.conf.js
Labels: frontend, need review

#1269 fix(TDP-5115): missing japanese translations
  dataprep-webapp/src/app/components/about/about.html
  dataprep-webapp/src/app/components/inventory/copy-move/inventory-copy-move-component.js
  dataprep-webapp/src/app/components/inventory/copy-move/inventory-copy-move.html
  dataprep-webapp/src/app/components/preparation/copy-move/preparation-copy-move-controller.js
  dataprep-webapp/src/app/components/preparation/copy-move/preparation-copy-move.html
  dataprep-webapp/src/app/components/suggestions-stats/stats-details/stats-details.html
  dataprep-webapp/src/app/services/statistics/statistics-service.js
  dataprep-webapp/src/app/services/statistics/statistics-service.spec.js
  dataprep-webapp/src/app/services/statistics/statistics-tooltip-service.spec.js
  dataprep-webapp/src/app/settings/actions/dataset-actions-service.js
  dataprep-webapp/src/app/settings/actions/preparation-actions-service.js
  dataprep-webapp/src/app/settings/actions/preparation-actions-service.spec.js
  dataprep-webapp/src/i18n/en.json
  dataprep-webapp/src/i18n/fr.json
  dataprep-webapp/src/i18n/ja.json
Labels: frontend, need review

#1262 fix(TDP-5481): popin is not display completely when message is too long
  dataprep-webapp/src/app/components/widgets/modal/_modal.scss
Labels: bug, frontend, need review

#1274 chore: update frontend libs
  dataprep-webapp/package.json
  dataprep-webapp/yarn.lock
Labels: bug, frontend, need review

#1276 fix(TDP-4690) Fix delete of all steps
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/preparation/Step.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/preparation/store/PersistentPreparationRepository.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/preparation/store/PersistentStep.java
  dataprep-maintenance/src/main/java/org/talend/dataprep/maintenance/preparation/PreparationCleaner.java
  dataprep-maintenance/src/main/java/org/talend/dataprep/maintenance/preparation/PreparationStepMarker.java
  dataprep-maintenance/src/test/java/org/talend/dataprep/maintenance/preparation/PreparationStepMarkerTest.java
Labels: backend, need review

#1285 chore(TDP-5502): Update Dataprep Dependencies for Spring'18
  dataprep-avro-message/pom.xml
  dataprep-backend/pom.xml
Labels: need review

#1287 Yacarof/fix/tdp 5548 uniformize use of tags in it
  dataprep-test-api/README.md
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java
  dataprep-test-api/src/test/resources/features/ChangeDatePatternActionTest.feature
  dataprep-test-api/src/test/resources/features/DatasetCache.feature
  dataprep-test-api/src/test/resources/features/ExportFormat.feature
  dataprep-test-api/src/test/resources/features/ExportFormatXLSXResult.feature
  dataprep-test-api/src/test/resources/features/ExportPreparationFromCSV.feature
  dataprep-test-api/src/test/resources/features/ExportPreparationFromXLSX.feature
  dataprep-test-api/src/test/resources/features/PreparationContent.feature
  dataprep-test-api/src/test/resources/features/SearchAndReplaceActionTest.feature
  dataprep-test-api/src/test/resources/features/SmokeTest.feature
  dataprep-test-api/src/test/resources/features/SplitActionTest.feature
  dataprep-test-api/src/test/resources/features/TrimActionTest.feature
Labels: backend, integration tests, need review

#1264 fix(TDP-5521): remove config.json need
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/uris/provider/UrisProvider.java
  dataprep-api/src/test/java/org/talend/dataprep/api/service/settings/UrisProviderTest.java
  dataprep-webapp/config/webpack.config.js
  dataprep-webapp/config/webpack.config.prod.js
  dataprep-webapp/src/app/components/about/about-component.spec.js
  dataprep-webapp/src/app/components/about/about-controller.js
  dataprep-webapp/src/app/components/about/about.html
  dataprep-webapp/src/app/components/app/app-directive.spec.js
  dataprep-webapp/src/app/components/export/export-controller.spec.js
  dataprep-webapp/src/app/components/preparation/creator/form/preparation-creator-form-controller.spec.js
  dataprep-webapp/src/app/index-config.js
  dataprep-webapp/src/app/index-module.js
  dataprep-webapp/src/app/services/about/about-service.spec.js
  dataprep-webapp/src/app/services/column-types/column-types-rest/column-types-rest-service.spec.js
  dataprep-webapp/src/app/services/dataset/rest/dataset-rest-service.spec.js
  dataprep-webapp/src/app/services/feedback/feedback-rest-service.spec.js
  dataprep-webapp/src/app/services/folder/rest/folder-rest-service.spec.js
  dataprep-webapp/src/app/services/preparation/rest/preparation-rest-service.spec.js
  dataprep-webapp/src/app/services/rest/rest-queued-message-interceptor-factory.js
  dataprep-webapp/src/app/services/rest/rest-queued-message-interceptor-factory.spec.js
  dataprep-webapp/src/app/services/search/inventory/rest/search-inventory-rest-service.spec.js
  dataprep-webapp/src/app/services/statistics/rest/statistics-rest-service.spec.js
  dataprep-webapp/src/app/services/utils/config/utils-copyrights-service.js
  dataprep-webapp/src/app/services/utils/config/utils-copyrights-service.spec.js
  dataprep-webapp/src/app/services/utils/config/utils-rest-urls-service.js
  dataprep-webapp/src/app/services/utils/config/utils-rest-urls-service.spec.js
  dataprep-webapp/src/app/services/utils/utils-module.js
  dataprep-webapp/src/app/settings/settings-service.spec.js
  dataprep-webapp/src/i18n/en.json
  dataprep-webapp/src/i18n/fr.json
  dataprep-webapp/src/i18n/ja.json
Labels: frontend, need review

#1289 Skermabon/tdp 5325 update semantic type multi tenant merge master
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java
Labels: need review

#1292 fix(TDP-5567): embed translations
  dataprep-webapp/config/webpack.config.js
  dataprep-webapp/src/app/index-module.js
  dataprep-webapp/src/i18n/index.js
  dataprep-webapp/src/i18n/ja.json
Labels: frontend, need review

#1280 feat(TDP-5529): Export fullrun for preparation with no step
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/BaseExportStrategy.java
Labels: backend, need review

#1294 fix(TDP-5567): Missing components tranlsations
  dataprep-webapp/src/app/index-module.js
Labels: frontend, need review

#1299 fix(TDP-5576): typo
  dataprep-webapp/src/i18n/en.json
Labels: need review

#1143 feat(TDP-5296): bootstrap react-cmf project
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/context/provider/ContextProvider.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/DatasetConfiguration.java
  dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties
  dataprep-webapp/.babelrc
  dataprep-webapp/cmf.json
  dataprep-webapp/config/license.js
  dataprep-webapp/config/sass.conf.js
  dataprep-webapp/config/webpack.config.dev.js
  dataprep-webapp/config/webpack.config.js
  dataprep-webapp/config/webpack.config.prod.js
  dataprep-webapp/config/webpack.config.test.js
  dataprep-webapp/karma.conf.js
  dataprep-webapp/package.json
  dataprep-webapp/pom.xml
  dataprep-webapp/src/app/components/playground/playground-controller.spec.js
  dataprep-webapp/src/app/components/preparation-creator/PreparationCreatorModal.component.js
  dataprep-webapp/src/app/components/preparation-creator/PreparationCreatorModal.connect.js
  dataprep-webapp/src/app/components/preparation-creator/index.js
  dataprep-webapp/src/app/components/suggestions-stats/stats-details/stats-details-directive.spec.js
  dataprep-webapp/src/app/configure.cmf.js
  dataprep-webapp/src/app/index-module.js
  dataprep-webapp/src/app/index.cmf.js
  dataprep-webapp/src/app/next/actions/__snapshots__/redirect.test.js.snap
  dataprep-webapp/src/app/next/actions/help.js
  dataprep-webapp/src/app/next/actions/index.js
  dataprep-webapp/src/app/next/actions/preparation.js
  dataprep-webapp/src/app/next/actions/redirect.js
  dataprep-webapp/src/app/next/actions/redirect.test.js
  dataprep-webapp/src/app/next/actions/version.js
  dataprep-webapp/src/app/next/components/AboutModal/AboutModal.component.js
  dataprep-webapp/src/app/next/components/AboutModal/AboutModal.connect.js
  dataprep-webapp/src/app/next/components/AboutModal/index.js
  dataprep-webapp/src/app/next/components/App.container.js
  dataprep-webapp/src/app/next/components/App.container.test.js
  dataprep-webapp/src/app/next/components/Version/Version.component.js
  dataprep-webapp/src/app/next/components/Version/Version.connect.js
  dataprep-webapp/src/app/next/components/Version/index.js
  dataprep-webapp/src/app/next/components/__snapshots__/App.container.test.js.snap
  dataprep-webapp/src/app/next/components/index.js
  dataprep-webapp/src/app/next/constants/index.js
  dataprep-webapp/src/app/next/reducers/index.js
  dataprep-webapp/src/app/next/sagas/help.saga.js
  dataprep-webapp/src/app/next/sagas/index.js
  dataprep-webapp/src/app/next/sagas/preparation.saga.js
  dataprep-webapp/src/app/next/sagas/version.saga.js
  dataprep-webapp/src/app/services/playground/playground-module.js
  dataprep-webapp/src/app/services/playground/playground-service.js
  dataprep-webapp/src/index.html
  dataprep-webapp/src/settings/settings.json
  dataprep-webapp/src/test/styleMock.js
  dataprep-webapp/test-setup.js
  dataprep-webapp/yarn.lock
Labels: frontend, need review

#1303 fix(TDP-5591): unable to list preparations when the attached dataset …
  dataprep-webapp/src/app/services/folder/folder-service.js
Labels: bug, frontend, need review
