Repository Talend/data-prep, pull requests merged in 2018-09, with the labels that each got.

#1585 fix: fix country converter
  dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
  dataprep-actions/src/main/resources/org/talend/dataprep/transformation/actions/conversions/country-codes.csv
Labels: backend, need review

#1482 chore(): active journalized content by default
  dataprep-dataset/src/main/resources/application.properties
  dataprep-transformation/src/main/resources/application.properties
Labels: need review

#1519 feat(TDP-5982): remove ExportStrategy interface
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/BaseTransformationService.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/ExportStrategy.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/ApplyPreparationExportStrategy.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/CachedExportStrategy.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/DataSetExportStrategy.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/OptimizedExportStrategy.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/PreparationExportStrategy.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/SampleExportStrategy.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/configuration/StandardExportStrategiesIntegrationTest.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/export/ApplyPreparationExportStrategyTest.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/export/CachedExportStrategyTest.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/export/OptimizedExportStrategyTest.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/export/PreparationExportStrategyTest.java
Labels: backend, enhancement, need review

#1587 chore: upgrade Talend/ui to 0.207.0
  dataprep-webapp/package.json
  dataprep-webapp/src/app/next/components/__snapshots__/App.container.test.js.snap
  dataprep-webapp/yarn.lock
Labels: frontend, need review

#1571 feat(TDP-5283): react cmf about
  dataprep-webapp/src/app/components/about/_about.scss
  dataprep-webapp/src/app/components/about/about-component.spec.js
  dataprep-webapp/src/app/components/about/about-controller.js
  dataprep-webapp/src/app/components/about/about-controller.spec.js
  dataprep-webapp/src/app/components/about/about.html
  dataprep-webapp/src/app/components/widgets-containers/widgets-containers-module.js
  dataprep-webapp/src/app/components/widgets/modal/_modal.scss
  dataprep-webapp/src/app/index.scss
  dataprep-webapp/src/app/next/components/AboutModal/AboutModal.component.js
  dataprep-webapp/src/app/next/components/AboutModal/AboutModal.component.test.js
  dataprep-webapp/src/app/next/components/AboutModal/AboutModal.connect.js
  dataprep-webapp/src/app/next/components/AboutModal/AboutModal.scss
  dataprep-webapp/src/app/next/components/AboutModal/__snapshots__/AboutModal.component.test.js.snap
  dataprep-webapp/src/app/next/components/AboutModal/index.js
  dataprep-webapp/src/app/next/components/App.container.js
  dataprep-webapp/src/app/next/components/App.container.test.js
  dataprep-webapp/src/app/next/components/__snapshots__/App.container.test.js.snap
  dataprep-webapp/src/app/next/components/index.js
  dataprep-webapp/src/app/next/locales/en/tui-components.json
  dataprep-webapp/src/app/next/locales/en/tui-forms.json
  dataprep-webapp/src/app/next/locales/fr/tui-components.json
  dataprep-webapp/src/app/next/locales/fr/tui-forms.json
  dataprep-webapp/src/app/next/locales/ja/tui-components.json
  dataprep-webapp/src/app/next/locales/ja/tui-forms.json
  dataprep-webapp/src/app/next/sagas/effects/__tests__/help.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/help.effects.js
  dataprep-webapp/src/app/next/settings/settings.json
  dataprep-webapp/src/app/services/about/about-service.js
  dataprep-webapp/src/app/services/state/home/home-state-service.js
  dataprep-webapp/src/app/services/state/home/home-state-service.spec.js
Labels: enhancement, frontend, need review

#1584 fix(TDP-5947): datasets listing has performance degradation
  dataprep-api/src/main/java/org/talend/dataprep/api/service/DataSetAPI.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/api/ActionDropdownSettings.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/DatasetActions.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/DatasetActionsProvider.java
  dataprep-api/src/test/java/org/talend/dataprep/api/service/AppSettingsAPITest.java
  dataprep-api/src/test/java/org/talend/dataprep/api/service/DataSetAPITest.java
  dataprep-api/src/test/java/org/talend/dataprep/api/service/test/APIClientTest.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/DataSetContent.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/DataSetGovernance.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/DatasetDTO.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/DatasetDetailsDTO.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/DatasetInjection.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/DefaultOwnerInjection.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/DefaultSharedInjection.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/Injections.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/OwnerInjection.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/SharedInjection.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/DatasetClient.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/conversions/DatasetBeanConversion.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/util/SortAndOrderHelper.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/dataset/adapter/conversions/DatasetBeanConversionTest.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/adapter/DataSetController.java
  dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java
  dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/DataSetServiceTest.java
  dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/dto/DatasetContent.java
  dataprep-webapp/package.json
  dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-controller.js
  dataprep-webapp/src/app/services/dataset/dataset-service.js
  dataprep-webapp/src/app/services/dataset/dataset-service.spec.js
  dataprep-webapp/src/app/services/dataset/list/dataset-list-service.js
  dataprep-webapp/src/app/services/dataset/list/dataset-list-service.spec.js
  dataprep-webapp/src/app/services/dataset/rest/dataset-rest-service.js
  dataprep-webapp/src/app/services/dataset/rest/dataset-rest-service.spec.js
  dataprep-webapp/src/app/settings/actions/dataset-actions-service.js
  dataprep-webapp/src/app/settings/actions/dataset-actions-service.spec.js
  dataprep-webapp/yarn.lock
Labels: backend, frontend, need review

#1591 fix(TDP-5227): about
  dataprep-webapp/src/app/components/about/about-controller.js
  dataprep-webapp/src/app/components/about/about-controller.spec.js
  dataprep-webapp/src/app/index-module.js
  dataprep-webapp/src/i18n/en.json
  dataprep-webapp/src/i18n/fr.json
  dataprep-webapp/src/i18n/ja.json
Labels: frontend, need review

#1570 feat(TDP-5286) add/remove folder
  dataprep-api/src/main/java/org/talend/dataprep/api/service/FolderAPI.java
  dataprep-webapp/src/app/configure.cmf.js
  dataprep-webapp/src/app/next/actions/__tests__/__snapshots__/folder.test.js.snap
  dataprep-webapp/src/app/next/actions/__tests__/__snapshots__/preparation.test.js.snap
  dataprep-webapp/src/app/next/actions/__tests__/folder.test.js
  dataprep-webapp/src/app/next/actions/__tests__/preparation.test.js
  dataprep-webapp/src/app/next/actions/folder.js
  dataprep-webapp/src/app/next/actions/preparation.js
  dataprep-webapp/src/app/next/components/App.container.js
  dataprep-webapp/src/app/next/components/App.scss
  dataprep-webapp/src/app/next/components/FolderCreatorModal/FolderCreatorModal.component.js
  dataprep-webapp/src/app/next/components/FolderCreatorModal/FolderCreatorModal.connect.js
  dataprep-webapp/src/app/next/components/FolderCreatorModal/index.js
  dataprep-webapp/src/app/next/components/index.js
  dataprep-webapp/src/app/next/constants/actions.js
  dataprep-webapp/src/app/next/locales/en/tdp-app.json
  dataprep-webapp/src/app/next/locales/en/tdp-cmf.json
  dataprep-webapp/src/app/next/locales/en/tui-components.json
  dataprep-webapp/src/app/next/locales/fr/tdp-app.json
  dataprep-webapp/src/app/next/locales/fr/tdp-cmf.json
  dataprep-webapp/src/app/next/locales/fr/tui-components.json
  dataprep-webapp/src/app/next/locales/ja/tdp-app.json
  dataprep-webapp/src/app/next/locales/ja/tdp-cmf.json
  dataprep-webapp/src/app/next/locales/ja/tui-components.json
  dataprep-webapp/src/app/next/sagas/effects/__tests__/preparation.effects.mock.js
  dataprep-webapp/src/app/next/sagas/effects/__tests__/preparation.effects.test.js
  dataprep-webapp/src/app/next/sagas/effects/http.effects.js
  dataprep-webapp/src/app/next/sagas/effects/preparation.effects.js
  dataprep-webapp/src/app/next/sagas/watchers/__tests__/preparation.saga.test.js
  dataprep-webapp/src/app/next/sagas/watchers/preparation.saga.js
  dataprep-webapp/src/app/next/settings/settings.json
Labels: frontend, need review

#1597 fix(TDP-5947): datasets listing has performance degradation
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/DatasetActionsProvider.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/views/provider/ListViews.java
  dataprep-api/src/test/java/org/talend/dataprep/api/service/AppSettingsAPITest.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/DatasetClient.java
Labels: backend, need review

#1601 fix(TDP-3597): add tooltip to action label
  dataprep-webapp/src/app/css/components/_tooltips.scss
Labels: frontend, need review

#1598 feat(TDQ-14358): Enable data masking of a column with the semantic type
  dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/datamasking/MaskDataByDomain.java
  dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/datamasking/MaskDataByDomainTest.java
  dataprep-api/src/main/java/org/talend/dataprep/api/service/PreparationAPI.java
  dataprep-backend-common/src/main/java/org/talend/dataprep/quality/AnalyzerService.java
Labels: need review

#1604 fix(TDP-1430): add loader to preview
  dataprep-webapp/src/app/components/playground/header/_playground-header.scss
  dataprep-webapp/src/app/components/playground/header/playground-header-component.js
  dataprep-webapp/src/app/components/playground/header/playground-header-component.spec.js
  dataprep-webapp/src/app/components/playground/header/playground-header.html
  dataprep-webapp/src/app/components/playground/playground.html
  dataprep-webapp/src/app/services/preview/preview-service.js
  dataprep-webapp/src/app/services/preview/preview-service.spec.js
  dataprep-webapp/src/app/services/state/playground/playground-state-service.js
  dataprep-webapp/src/app/services/state/playground/playground-state-service.spec.js
  dataprep-webapp/src/app/services/state/state-service.js
Labels: frontend, need review

#1600 fix(TDP-6045): lookup panel loading
  dataprep-webapp/src/app/components/lookup/_lookup.scss
  dataprep-webapp/src/app/components/lookup/lookup-directive.js
  dataprep-webapp/src/app/components/lookup/lookup-directive.spec.js
  dataprep-webapp/src/app/components/lookup/lookup.html
  dataprep-webapp/src/app/components/playground/header/playground-header-component.js
  dataprep-webapp/src/app/components/playground/header/playground-header-component.spec.js
  dataprep-webapp/src/app/components/playground/header/playground-header.html
  dataprep-webapp/src/app/components/playground/playground-controller.js
  dataprep-webapp/src/app/components/playground/playground-controller.spec.js
  dataprep-webapp/src/app/components/playground/playground.html
  dataprep-webapp/src/app/services/lookup/lookup-service.js
  dataprep-webapp/src/app/services/lookup/lookup-service.spec.js
  dataprep-webapp/src/app/services/state/lookup/lookup-state-service.js
  dataprep-webapp/src/app/services/state/lookup/lookup-state-service.spec.js
  dataprep-webapp/src/app/services/state/playground/playground-state-service.js
  dataprep-webapp/src/app/services/state/state-service.js
Labels: frontend, need review

#1608 chore: html lang attribute
  dataprep-webapp/src/app/index-module.js
  dataprep-webapp/src/app/services/utils/click/disable-right-click-directive.js
  dataprep-webapp/src/app/services/utils/click/disable-right-click-directive.spec.js
  dataprep-webapp/src/app/services/utils/html/htmlLang-directive.js
  dataprep-webapp/src/app/services/utils/utils-module.js
  dataprep-webapp/src/index.html
Labels: frontend, need review

#1606 fix(TDP-5518): add loader when retrieving semantic types
  dataprep-webapp/src/app/components/datagrid/header/datagrid-header-controller.js
  dataprep-webapp/src/app/components/datagrid/header/datagrid-header.html
  dataprep-webapp/src/app/components/loader/_loader.scss
  dataprep-webapp/src/app/components/loader/loader.component.js
  dataprep-webapp/src/app/components/loader/loader.component.spec.js
  dataprep-webapp/src/app/components/loader/loader.html
  dataprep-webapp/src/i18n/en.json
  dataprep-webapp/src/i18n/fr.json
  dataprep-webapp/src/i18n/ja.json
Labels: frontend, need review

#1582 feat(TDP-5782): pendo on prem
  dataprep-backend-service/src/main/java/org/talend/dataprep/analytics/Analytics.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/configuration/DataPrepComponentScanConfiguration.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/security/NoOpSecurity.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/security/Security.java
  dataprep-backend-service/src/test/java/org/talend/dataprep/command/GenericCommandTest.java
Labels: backend, need review

#1583 feat(TDP-6005): Configure and log first event to LogServer
  dataprep-backend-service-parent/pom.xml
  dataprep-backend-service/src/main/java/org/talend/dataprep/audit/BaseDataprepAuditService.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/audit/NoOpAuditService.java
  dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/FolderService.java
  dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
  dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/PreparationServiceUnitTest.java
Labels: backend, enhancement, need review

#1588 feat(TDP-5926) update spring cloud dependencies
  dataprep-async-runtime/pom.xml
  dataprep-async-runtime/src/test/resources/application.properties
  dataprep-backend-service-parent/pom.xml
  dataprep-backend-service/pom.xml
  dataprep-backend/pom.xml
  pom.xml
Labels: backend, need review, reviewing

#1624 chore(TDP-4404): add labels
  dataprep-webapp/src/i18n/en.json
Labels: frontend, need review

#1617 fix(TDP-5518): loading while retrieving semantic types
  dataprep-webapp/src/app/components/datagrid/header/datagrid-header-controller.js
  dataprep-webapp/src/app/components/datagrid/header/datagrid-header-controller.spec.js
  dataprep-webapp/src/app/components/datagrid/header/datagrid-header-directive.spec.js
  dataprep-webapp/src/app/components/datagrid/header/datagrid-header.html
  dataprep-webapp/src/app/components/transformation/menu/transformation-menu-directive.js
  dataprep-webapp/src/app/components/transformation/menu/transformation-menu-directive.spec.js
  dataprep-webapp/src/app/components/transformation/menu/transformation-menu.html
  dataprep-webapp/src/app/components/transformation/menu/type/type-transformation-menu-component.js
  dataprep-webapp/src/app/components/transformation/menu/type/type-transformation-menu-component.spec.js
  dataprep-webapp/src/app/components/transformation/menu/type/type-transformation-menu.html
Labels: frontend, need review

#1610 fix(TDP-1251): refresh lookup dataset list
  dataprep-webapp/src/app/components/lookup/lookup-controller.js
  dataprep-webapp/src/app/components/lookup/lookup-controller.spec.js
  dataprep-webapp/src/app/components/lookup/lookup.html
  dataprep-webapp/src/app/components/widgets/navigation-list/navigation-list.html
  dataprep-webapp/src/app/components/widgets/navigation-list/widget-navigation-list-directive.js
  dataprep-webapp/src/app/components/widgets/navigation-list/widget-navigation-list-directive.spec.js
  dataprep-webapp/src/app/services/lookup/lookup-service.js
  dataprep-webapp/src/app/services/lookup/lookup-service.spec.js
  dataprep-webapp/src/app/services/state/lookup/lookup-state-service.js
  dataprep-webapp/src/app/services/state/lookup/lookup-state-service.spec.js
  dataprep-webapp/src/app/services/state/playground/playground-state-service.js
  dataprep-webapp/src/app/services/state/state-service.js
Labels: frontend, need review

#1621 fix(TDP-6050): stream export create empty files
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/BaseExportStrategy.java
Labels: backend, bug, need review

#1631 fix(TDP-6097): fix TQL translation to 'complies pattern'
  dataprep-backend-common/src/main/java/org/talend/dataprep/api/filter/FilterTranslator.java
  dataprep-backend-common/src/test/java/org/talend/dataprep/api/filter/FilterTranslatorTest.java
Labels: backend, bug, need review

#1487 chore(TDP-5900 -> TDP-5903): Pipeline performance improvements
  dataprep-api/src/test/java/org/talend/dataprep/api/service/PreparationAPITest.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/cache/loader/ResourceLoaderContentCache.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/command/GenericCommand.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/DataSetNameInjection.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/lock/store/LockedResourceRepository.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/preparation/store/PersistentPreparationRepository.java
  dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties
  dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/MetadataChangesOnActionsGenerator.java
  dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/FileStep.java
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/FilterStep.java
  dataprep-test-api/src/test/resources/features/Filter.feature
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/json/PipelineDiffTransformer.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/json/PipelineTransformer.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/pipeline/model/WriterNode.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/ReactiveStepMetadataRepository.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/RemoteStepMetadataRepository.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/StepMetadataRepository.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/StepMetadataRepositoryConfiguration.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationRowMetadataUtils.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/ApplyPreparationExportStrategy.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/CachedExportStrategy.java
  dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/OptimizedExportStrategy.java
  dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/TransformationServiceBaseTest.java
Labels: Work in progress, backend

#1616 feat(TDP-4839): hdfs streams export ti
  dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/FeatureContext.java
Labels: integration tests

#1620 feat(TDP-4404): word based patterns
  dataprep-api/src/test/java/org/talend/dataprep/api/service/PreparationAPITest.java
  dataprep-api/src/test/java/org/talend/dataprep/api/service/test/APIClientTest.java
  dataprep-api/src/test/resources/org/talend/dataprep/api/service/dataset/TDP-4404_data_for_word_pattern_recognition.txt
  dataprep-api/src/test/resources/org/talend/dataprep/api/service/dataset/TDP-4404_data_for_word_pattern_recognition_result.txt
  dataprep-backend-service/src/main/java/org/talend/dataprep/cache/loader/ResourceLoaderContentCache.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/BeanConversionService.java
  dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/store/content/DataSetContentStore.java
  dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/DataSetServiceTest.java
  dataprep-dataset/src/test/resources/org/talend/dataprep/dataset/date_time_pattern_expected.json
  dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/format/expected_json_with_row_and_metadata.json
  dataprep-webapp/package.json
  dataprep-webapp/src/app/components/filter/bar/filter-bar.html
  dataprep-webapp/src/app/components/filter/item/_filter-item.scss
  dataprep-webapp/src/app/components/suggestions-stats/stats-details/_stats-details.scss
  dataprep-webapp/src/app/components/suggestions-stats/stats-details/stats-details-controller.js
  dataprep-webapp/src/app/components/suggestions-stats/stats-details/stats-details-controller.spec.js
  dataprep-webapp/src/app/components/suggestions-stats/stats-details/stats-details.html
  dataprep-webapp/src/app/components/suggestions-stats/suggestions-stats-module.js
  dataprep-webapp/src/app/components/widgets-containers/widgets-containers-module.js
  dataprep-webapp/src/app/services/filter/adapter/tql-filter-adapter-service.js
  dataprep-webapp/src/app/services/filter/adapter/tql-filter-adapter-service.spec.js
  dataprep-webapp/src/app/services/filter/filter-service.js
  dataprep-webapp/src/app/services/filter/filter-service.spec.js
  dataprep-webapp/src/app/services/filter/manager/filter-manager-service.js
  dataprep-webapp/src/app/services/filter/manager/filter-manager-service.spec.js
  dataprep-webapp/src/app/services/state/playground/playground-state-service.js
  dataprep-webapp/src/app/services/state/state-service.js
  dataprep-webapp/src/app/services/state/statistics/statistics-state-service.js
  dataprep-webapp/src/app/services/state/statistics/statistics-state-services.spec.js
  dataprep-webapp/src/app/services/statistics/pattern-occurence.worker.js
  dataprep-webapp/src/app/services/statistics/statistics-service.js
  dataprep-webapp/src/app/services/statistics/statistics-tooltip-service.js
  dataprep-webapp/src/app/services/statistics/statistics-tooltip-service.spec.js
  dataprep-webapp/yarn.lock
Labels: Work in progress, backend, frontend, need review, reviewing

#1650 fix(TDP-6127): fix the hidden "Apply to all cells" problem
  dataprep-webapp/src/app/components/datagrid/_datagrid.scss
Labels: frontend, need review
